/**
 * agent-environment family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const AGENT_ENVIRONMENT_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'hierarchical-task-oriented-agent',
    name: 'Hierarchical Task-Oriented Agent',
    archetype: 'agent-environment',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Multi-Modal & Temporal Fusion/Hierarchical Task-Oriented Agent.md',
    analogy: 'Information enters at multi-modal input processing and ends at fusion layer.',
    stages: [
      { id: 'multi_modal_input_processi', role: 'transform', label: 'Multi-Modal Input Processing' },
      { id: 'modality_specific_encoders', role: 'transform', label: 'Modality-Specific Encoders' },
      { id: 'time_series', role: 'transform', label: 'Time-Series', detail: 'LSTM, GRU, or Temporal CNN.' },
      { id: 'text', role: 'transform', label: 'Text', detail: 'Transformer (e.g., BERT) or word embeddings.' },
      { id: 'graphs', role: 'transform', label: 'Graphs', detail: 'GNN (e.g., GCN, GAT).' },
      { id: 'fusion_layer', role: 'transform', label: 'Fusion Layer', detail: 'Attention, concatenation, or MLP to combine modalities into state \\( s_t \\).' },
    ],
    beats: [
      { id: 'b1', at: 'time_series', label: 'Multi-Modal Input Processing', detail: 'Multi-Modal Input Processing' },
      { id: 'b2', at: 'multi_modal_input_processi', label: 'Modality-Specific Encoders', detail: 'Modality-Specific Encoders' },
      { id: 'b3', at: 'graphs', label: 'Time-Series', detail: 'LSTM, GRU, or Temporal CNN.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'multi-modal-reasoning-agent',
    name: 'Multi-Modal Reasoning Agent',
    archetype: 'agent-environment',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Multi-Modal & Temporal Fusion/Multi-Modal Reasoning Agent.md',
    analogy: 'Information enters at modality-specific encoders and ends at fusion module.',
    stages: [
      { id: 'modality_specific_encoders', role: 'transform', label: 'Modality-Specific Encoders' },
      { id: 'time_series', role: 'transform', label: 'Time-Series', detail: 'LSTM, GRU, or Temporal CNN for sequential data.' },
      { id: 'text', role: 'transform', label: 'Text', detail: 'Transformer (e.g., BERT) or embeddings for sentiment or news.' },
      { id: 'images', role: 'transform', label: 'Images', detail: 'CNN (e.g., ResNet) for visual market indicators.' },
      { id: 'graphs', role: 'transform', label: 'Graphs', detail: 'GNN (e.g., GCN, GAT) for relational data (e.g., asset correlations).' },
      { id: 'fusion_module', role: 'transform', label: 'Fusion Module' },
    ],
    beats: [
      { id: 'b1', at: 'images', label: 'Modality-Specific Encoders', detail: 'Modality-Specific Encoders' },
      { id: 'b2', at: 'time_series', label: 'Time-Series', detail: 'LSTM, GRU, or Temporal CNN for sequential data.' },
      { id: 'b3', at: 'graphs', label: 'Text', detail: 'Transformer (e.g., BERT) or embeddings for sentiment or news.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
];
