/**
 * autoregressive family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const AUTOREGRESSIVE_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'autoregressive-model-pixelrnn-pixelcnn',
    name: 'Autoregressive Models (PixelRNN and PixelCNN)',
    archetype: 'autoregressive',
    provenance: 'schematic',
    specPath: 'Generative Models/Autoregressive/Autoregressive Model (PixelRNN, PixelCNN).md',
    analogy: 'Information enters at explicit likelihood and ends at slow sampling.',
    stages: [
      { id: 'explicit_likelihood', role: 'loss', label: 'Explicit Likelihood', detail: 'Provides tractable log-likelihoods, enabling quantitative evaluation.' },
      { id: 'high_quality_samples', role: 'transform', label: 'High-Quality Samples', detail: 'Generates sharp, diverse images, competitive with GANs.' },
      { id: 'sequential_generation', role: 'transform', label: 'Sequential Generation', detail: 'Models pixel dependencies in a fixed order, ensuring coherence.' },
      { id: 'conditional_generation', role: 'transform', label: 'Conditional Generation', detail: 'Supports conditioning on labels, embeddings, or partial images.' },
      { id: 'slow_sampling', role: 'transform', label: 'Slow Sampling', detail: 'Sequential generation limits speed compared to GANs.' },
    ],
    beats: [
      { id: 'b1', at: 'explicit_likelihood', label: 'Explicit Likelihood', detail: 'Provides tractable log-likelihoods, enabling quantitative evaluation.' },
      { id: 'b2', at: 'sequential_generation', label: 'High-Quality Samples', detail: 'Generates sharp, diverse images, competitive with GANs.' },
      { id: 'b3', at: 'high_quality_samples', label: 'Sequential Generation', detail: 'Models pixel dependencies in a fixed order, ensuring coherence.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
];
