/**
 * density-boundary family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const DENSITY_BOUNDARY_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'semi-supervised-svm-s3vm',
    name: 'Semi-Supervised Support Vector Machine (S3VM)',
    archetype: 'density-boundary',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Margin-Based Methods/Support Vector Machine (SVM).md',
    analogy: 'Information enters at decision boundary and ends at dataset.',
    stages: [
      { id: 'decision_boundary', role: 'transform', label: 'Decision boundary', detail: ', where is the weight vector, is the bias.' },
      { id: 'margin', role: 'transform', label: 'Margin', detail: 'Distance to support vectors, given by .' },
      { id: 'objective_function_soft_ma', role: 'loss', label: 'Objective function (soft-margin SVM)' },
      { id: 'subject_to', role: 'transform', label: 'Subject to', detail: ', , where are slack variables, is the regularization parameter, are labels.' },
      { id: 'kernelized_form', role: 'transform', label: 'Kernelized form', detail: 'Uses a kernel (e.g., for RBF) to compute inner products in a higher-dimensional space.' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector, for binary classification.' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Maximum Margin', detail: 'Identifies the hyperplane that maximizes the distance to the nearest data points (support vectors) from each class.' },
      { id: 'b2', at: 'subject_to', label: 'Soft Margin', detail: 'Allows some misclassifications with a penalty to handle noisy data, controlled by a regularization parameter.' },
      { id: 'b3', at: 'objective_function_soft_ma', label: 'Kernel Trick', detail: 'Maps data to higher-dimensional spaces to handle non-linear relationships using kernel functions (e.g., linear, RBF, polynomial).' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'lof-local-outlier-factor',
    name: 'Local Outlier Factor (LOF)',
    archetype: 'density-boundary',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Anomaly Detection/LOF (Local Outlier Factor).md',
    analogy: 'Information enters at reachability distance and ends at dataset.',
    stages: [
      { id: 'reachability_distance', role: 'score', label: 'Reachability Distance', detail: 'For a point and neighbor , , where is the distance to ’s -th nearest neighbor.' },
      { id: 'local_reachability_density', role: 'transform', label: 'Local Reachability Density (LRD)', detail: 'For a point , , where is the set of -nearest neighbors.' },
      { id: 'lof_score', role: 'score', label: 'LOF Score', detail: '.' },
      { id: 'point_has_similar_density_', role: 'transform', label: 'Point has similar density to neighbors (normal)' },
      { id: 'point_has_lower_density_an', role: 'transform', label: 'Point has lower density (anomaly)' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector (no labels required).' },
    ],
    beats: [
      { id: 'b1', at: 'point_has_lower_density_an', label: 'Local Density', detail: 'Computes the density of a point based on its distance to its -nearest neighbors, comparing it to the density of those neighbors.' },
      { id: 'b2', at: 'dataset', label: 'Outlier Scoring', detail: 'Assigns an anomaly score (LOF) where values significantly greater than 1 indicate outliers due to lower local density.' },
      { id: 'b3', at: 'reachability_distance', label: 'No Distributional Assumptions', detail: 'Does not assume a specific data distribution, handling non-linear and heterogeneous Forex data.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'one-class-svm',
    name: 'One-Class SVM',
    archetype: 'density-boundary',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Anomaly Detection/One-Class SVM.md',
    analogy: 'Information enters at objective and ends at hyperparameters.',
    stages: [
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Find a hyperplane that separates normal data from the origin with maximum margin in a feature space defined by' },
      { id: 'objective_function', role: 'loss', label: 'Objective function' },
      { id: 'subject_to', role: 'transform', label: 'Subject to', detail: ', , where are slack variables, controls the fraction of outliers.' },
      { id: 'kernel', role: 'transform', label: 'Kernel', detail: '(e.g., RBF: ).' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector (unlabeled, assumed mostly normal).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: '(outlier fraction), kernel type, kernel parameter (e.g., for RBF).' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Maximum Margin', detail: 'Finds a hyperplane that maximizes the margin around normal data in a high-dimensional space.' },
      { id: 'b2', at: 'kernel', label: 'Kernel Trick', detail: 'Uses kernel functions (e.g., RBF) to model non-linear boundaries, capturing complex Forex data patterns.' },
      { id: 'b3', at: 'dataset', label: 'Outlier Detection', detail: 'Classifies points far from the hyperplane as anomalies, assuming they deviate from the normal data distribution.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'robust-covariance-estimation',
    name: 'Robust Covariance Estimation',
    archetype: 'density-boundary',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Anomaly Detection/Robust Covariance Estimation.md',
    analogy: 'Information enters at data distribution and ends at hyperparameters.',
    stages: [
      { id: 'data_distribution', role: 'input', label: 'Data distribution', detail: ', where is the mean, is the covariance matrix.' },
      { id: 'mahalanobis_distance', role: 'score', label: 'Mahalanobis distance', detail: '.' },
      { id: 'anomaly_score', role: 'score', label: 'Anomaly score', detail: 'High indicates an anomaly (e.g., exceeding a chi-squared threshold).' },
      { id: 'mcd_objective', role: 'loss', label: 'MCD objective', detail: 'Find the subset of points (where , is feature dimension) with the smallest covariance determinant: .' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector (no labels required).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Fraction of clean data ( ), contamination ratio, support fraction.' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Multivariate Gaussian Model', detail: 'Assumes normal data follows a multivariate Gaussian distribution, with anomalies having low probability.' },
      { id: 'b2', at: 'data_distribution', label: 'Robust Estimation', detail: 'Uses methods like MCD to estimate mean and covariance, minimizing the impact of outliers.' },
      { id: 'b3', at: 'hyperparameters', label: 'Mahalanobis Distance', detail: 'Measures the distance of a point from the distribution’s center, adjusted for covariance, to score anomalies.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
];
