/**
 * encode-bottleneck-decode family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const ENCODE_BOTTLENECK_DECODE_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'masked-autoencoder-for-distribution-learning',
    name: 'Masked Autoencoder for Distribution Learning',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Generative Models/Latent Variable Models/Masked Autoencoder for Distribution Learning.md',
    analogy: 'Information enters at input preprocessing and ends at patch embedding.',
    stages: [
      { id: 'input_preprocessing', role: 'input', label: 'Input Preprocessing' },
      { id: 'random_masking', role: 'transform', label: 'Random masking', detail: 'A high fraction (e.g., 75%) of patches are masked (replaced with a learnable token or zeroed out), leaving vis' },
      { id: 'example', role: 'transform', label: 'Example', detail: 'A 224×224 image with 16×16 patches yields 196 patches, with ~49 visible after 75% masking.' },
      { id: 'maps_visible_patches_to_a_', role: 'latent', label: 'Maps visible patches to a latent representation' },
      { id: 'structure_vision_transform', role: 'transform', label: 'Structure (Vision Transformer-based)' },
      { id: 'patch_embedding', role: 'latent', label: 'Patch embedding', detail: 'Linear projection of patches to a fixed dimension (e.g., 768 for ViT-Base).' },
    ],
    beats: [
      { id: 'b1', at: 'maps_visible_patches_to_a_', label: 'Scalable Architecture', detail: 'Efficiently handles large datasets with high mask ratios.' },
      { id: 'b2', at: 'input_preprocessing', label: 'Robust Representations', detail: 'Learns generalizable features via masking.' },
      { id: 'b3', at: 'patch_embedding', label: 'Stable Training', detail: 'No adversarial dynamics, unlike GANs.' },
    ],
    repoRunner: { templateId: 'pytorch_autoencoder', note: 'Trained here through the generic pytorch_autoencoder template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'variational-autoencoder-vae',
    name: 'Variational Autoencoder (VAE)',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Generative Models/Latent Variable Models/Variational Autoencoder (VAE).md',
    analogy: 'Information enters at encoder and ends at decoder.',
    stages: [
      { id: 'encoder', role: 'transform', label: 'Encoder', detail: 'Maps input \\( x \\) to latent parameters \\( \\mu \\) and \\( \\sigma \\). Typically a neural network (e.g., MLP or C' },
      { id: 'decoder', role: 'transform', label: 'Decoder', detail: 'Maps latent variable \\( z \\) back to the data space, modeling \\( p(x|z) \\). Also a neural network, outputting ' },
    ],
    beats: [
      { id: 'b1', at: 'encoder', label: 'Encoder', detail: 'Maps input \\( x \\) to latent parameters \\( \\mu \\) and \\( \\sigma \\). Typically a neural network (e.g., MLP or CNN) outputting the mean and log-variance of \\( q(z|x) \\).' },
      { id: 'b2', at: 'decoder', label: 'Decoder', detail: 'Maps latent variable \\( z \\) back to the data space, modeling \\( p(x|z) \\). Also a neural network, outputting parameters of the data distribution (e.g., mean for Gaussian, probabilities for ' },
    ],
    repoRunner: { templateId: 'pytorch_vae', note: 'Trained here through the generic pytorch_vae template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'masked-autoencoder-mae',
    name: 'Masked Autoencoder (MAE)',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Machine Learning/Self-Supervised Learning/Masked Modeling/Masked Autoencoder (MAE).md',
    analogy: 'Information enters at for time-series and ends at optional components.',
    stages: [
      { id: 'for_time_series', role: 'transform', label: 'For time-series', detail: 'Transformer or LSTM processing temporal segments.' },
      { id: 'masking_module', role: 'transform', label: 'Masking Module' },
      { id: 'masking_strategy', role: 'transform', label: 'Masking strategy', detail: 'Uniform random or block-based.' },
      { id: 'pretraining', role: 'transform', label: 'Pretraining', detail: 'Reconstructed input for loss computation.' },
      { id: 'downstream', role: 'transform', label: 'Downstream', detail: 'Encoder features for tasks like classification.' },
      { id: 'optional_components', role: 'transform', label: 'Optional Components' },
    ],
    beats: [
      { id: 'b1', at: 'masking_strategy', label: 'For time-series', detail: 'Transformer or LSTM processing temporal segments.' },
      { id: 'b2', at: 'pretraining', label: 'Masking Module', detail: 'Masking Module' },
      { id: 'b3', at: 'optional_components', label: 'Masking strategy', detail: 'Uniform random or block-based.' },
    ],
    repoRunner: { templateId: 'pytorch_autoencoder', note: 'Trained here through the generic pytorch_autoencoder template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'ladder-network',
    name: 'Ladder Network',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Machine Learning/Semi-Supervised Learning/Generative & Hybrid Models/Ladder Network.md',
    analogy: 'Information enters at noisy encoder and ends at classification head.',
    stages: [
      { id: 'noisy_encoder', role: 'transform', label: 'Noisy Encoder' },
      { id: 'clean_encoder_optional', role: 'transform', label: 'Clean Encoder (optional)' },
      { id: 'often_omitted_in_practice_', role: 'transform', label: 'Often omitted in practice to simplify training' },
      { id: 'lateral_connections', role: 'transform', label: 'Lateral Connections' },
      { id: 'example', role: 'transform', label: 'Example', detail: ', where BN is batch normalization.' },
      { id: 'classification_head', role: 'score', label: 'Classification Head' },
    ],
    beats: [
      { id: 'b1', at: 'lateral_connections', label: 'Denoising Autoencoding', detail: 'Learns to reconstruct clean inputs from noisy versions, capturing robust features from unlabeled data.' },
      { id: 'b2', at: 'often_omitted_in_practice_', label: 'Hierarchical Representation', detail: 'Uses a multi-layer architecture with lateral connections to integrate encoder and decoder features at each level.' },
      { id: 'b3', at: 'example', label: 'Supervised and Unsupervised Learning', detail: 'Combines a supervised classification loss for labeled data with an unsupervised reconstruction loss for all data.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'autoencoder-unsupervised',
    name: 'Autoencoder (Unsupervised)',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Matrix Factorization & Decomposition/Autoencoder (Unsupervised).md',
    analogy: 'Information enters at encoder and ends at hyperparameters.',
    stages: [
      { id: 'encoder', role: 'transform', label: 'Encoder', detail: ', where is the input, is the latent representation ( ), is a neural network with parameters .' },
      { id: 'decoder', role: 'transform', label: 'Decoder', detail: ', where is the reconstructed output, is a neural network with parameters .' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize reconstruction loss, typically mean squared error (MSE)' },
      { id: 'alternative_losses', role: 'loss', label: 'Alternative losses', detail: 'Binary cross-entropy for normalized data, or custom losses for specific tasks.' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector.' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Latent dimension , network architecture, loss function, optimizer.' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Encoder-Decoder Architecture', detail: 'The encoder compresses input data into a latent representation; the decoder reconstructs the input from this representation.' },
      { id: 'b2', at: 'dataset', label: 'Latent Space', detail: 'A lower-dimensional space that captures essential data features, enabling dimensionality reduction.' },
      { id: 'b3', at: 'alternative_losses', label: 'Reconstruction Loss', detail: 'Minimizes the difference between input and reconstructed output, ensuring meaningful latent representations.' },
    ],
    repoRunner: { templateId: 'pytorch_autoencoder', note: 'Trained here through the generic pytorch_autoencoder template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'u-net',
    name: 'U-Net',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Convolutional Networks/U-Net.md',
    analogy: 'Information enters at input and ends at each block.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Grid-like data (e.g., candlestick chart) or (time-series formatted as 2D), where are image dimensions, is chan' },
      { id: 'encoder', role: 'transform', label: 'Encoder', detail: 'Stack of convolutional blocks' },
      { id: 'each_block', role: 'transform', label: 'Each block', detail: 'Two 3x3 convolutions with ReLU and batch normalization, followed by max-pooling (2x2, stride 2) to reduce dime' },
      { id: 'bottleneck', role: 'latent', label: 'Bottleneck', detail: 'Deepest layer with high-level features (e.g., 1024 channels).' },
      { id: 'decoder', role: 'transform', label: 'Decoder', detail: 'Symmetric stack of upsampling blocks' },
      { id: 'each_block_2', role: 'transform', label: 'Each block', detail: 'Upsampling (e.g., transposed convolution or bilinear interpolation), concatenation with encoder features via s' },
    ],
    beats: [
      { id: 'b1', at: 'each_block', label: 'Encoder-Decoder Structure', detail: 'The encoder extracts hierarchical features via convolutions and pooling; the decoder upsamples features to reconstruct detailed outputs.' },
      { id: 'b2', at: 'each_block_2', label: 'Skip Connections', detail: 'Concatenates encoder features with decoder layers to retain fine-grained details, critical for precise pattern detection.' },
      { id: 'b3', at: 'input', label: 'Convolutional Layers', detail: 'Applies filters to capture local patterns (e.g., candlestick shapes, price trends).' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'autoencoder-ae',
    name: 'Autoencoder (AE)',
    archetype: 'encode-bottleneck-decode',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Matrix Factorization & Decomposition/Autoencoder (Unsupervised).md',
    analogy: 'Information enters at encoder and ends at hyperparameters.',
    stages: [
      { id: 'encoder', role: 'transform', label: 'Encoder', detail: ', where is the input, is the latent representation ( ), is a neural network with parameters .' },
      { id: 'decoder', role: 'transform', label: 'Decoder', detail: ', where is the reconstructed output, is a neural network with parameters .' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize reconstruction loss, typically mean squared error (MSE)' },
      { id: 'alternative_losses', role: 'loss', label: 'Alternative losses', detail: 'Binary cross-entropy for normalized data, or custom losses for specific tasks.' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector.' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Latent dimension , network architecture, loss function, optimizer.' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Encoder-Decoder Architecture', detail: 'The encoder compresses input data into a latent representation; the decoder reconstructs the input from this representation.' },
      { id: 'b2', at: 'dataset', label: 'Latent Space', detail: 'A lower-dimensional space that captures essential data features, enabling dimensionality reduction.' },
      { id: 'b3', at: 'alternative_losses', label: 'Reconstruction Loss', detail: 'Minimizes the difference between input and reconstructed output, ensuring meaningful latent representations.' },
    ],
    repoRunner: { templateId: 'pytorch_autoencoder', note: 'Trained here through the generic pytorch_autoencoder template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
];
