/**
 * ensemble-route family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const ENSEMBLE_ROUTE_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'stacked-ensemble-model',
    name: 'Stacked Ensemble Model',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Classical Hybrids/Stacked Ensemble Model.md',
    analogy: 'Information enters at level-0 (base models) and ends at support vector machines.',
    stages: [
      { id: 'level_0_base_models', role: 'transform', label: 'Level-0 (Base Models)', detail: 'A set of heterogeneous models, such as' },
      { id: 'decision_trees_random_fore', role: 'transform', label: 'Decision Trees, Random Forests' },
      { id: 'gradient_boosting_e_g_xgbo', role: 'update', label: 'Gradient Boosting (e.g., XGBoost, LightGBM)' },
      { id: 'neural_networks_e_g_mlps_c', role: 'transform', label: 'Neural Networks (e.g., MLPs, CNNs)' },
      { id: 'linear_models_e_g_logistic', role: 'transform', label: 'Linear Models (e.g., logistic regression)' },
      { id: 'support_vector_machines', role: 'transform', label: 'Support Vector Machines' },
    ],
    beats: [
      { id: 'b1', at: 'linear_models_e_g_logistic', label: 'Level-0 (Base Models)', detail: 'A set of heterogeneous models, such as' },
      { id: 'b2', at: 'decision_trees_random_fore', label: 'Decision Trees, Random Forests', detail: 'Decision Trees, Random Forests' },
      { id: 'b3', at: 'level_0_base_models', label: 'Gradient Boosting (e.g., XGBoost, LightGBM)', detail: 'Gradient Boosting (e.g., XGBoost, LightGBM)' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'calibrated-classifier',
    name: 'Calibrated Classifier',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Calibration & Meta-Learners/Calibrated Classifier.md',
    analogy: 'Information enters at platt scaling and ends at suitable for both binary and multi-class problems.',
    stages: [
      { id: 'platt_scaling', role: 'transform', label: 'Platt Scaling' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize negative log-likelihood on a calibration set.' },
      { id: 'isotonic_regression', role: 'transform', label: 'Isotonic Regression' },
      { id: 'suitable_for_both_binary_a', role: 'transform', label: 'Suitable for both binary and multi-class problems' },
    ],
    beats: [
      { id: 'b1', at: 'platt_scaling', label: 'Probability Calibration', detail: 'Adjusts raw classifier scores to produce probabilities that match empirical frequencies, improving decision-making reliability.' },
      { id: 'b2', at: 'objective', label: 'Meta-Learning', detail: 'Trains a secondary model (calibrator) on top of a base classifier to map raw scores to calibrated probabilities.' },
      { id: 'b3', at: 'suitable_for_both_binary_a', label: 'Confidence Alignment', detail: 'Ensures predicted probabilities reflect true likelihoods, critical for risk-sensitive applications like trading.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'hypernetwork',
    name: 'Hypernetwork',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Memory & Routing Architectures/Hypernetwork.md',
    analogy: 'Information enters at input and ends at objective.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Context or input data (e.g., market features like volatility, OHLC, or indicators) and primary input (e.g., OH' },
      { id: 'hypernetwork', role: 'transform', label: 'Hypernetwork', detail: 'Generates weights for the target network' },
      { id: 'context_e_g_market_indicat', role: 'latent', label: 'Context (e.g., market indicators, time-series embeddings)' },
      { id: 'target_network', role: 'transform', label: 'Target Network', detail: 'Processes input using generated weights' },
      { id: 'target_network_e_g_mlp_cnn', role: 'transform', label: 'Target network (e.g., MLP, CNN),', detail: 'Output (e.g., price prediction, signal).' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize task-specific loss (e.g., MSE for regression)' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Weight Generation', detail: 'A hypernetwork (a neural network) generates weights for a target network, conditioned on input data or context.' },
      { id: 'b2', at: 'target_network', label: 'Adaptive Modeling', detail: 'Adjusts target network parameters dynamically, enabling task-specific or condition-specific predictions.' },
      { id: 'b3', at: 'hypernetwork', label: 'Hierarchical Architecture', detail: 'Separates weight generation (hypernetwork) from task execution (target network), enhancing flexibility.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'mixture-of-experts',
    name: 'Mixture of Experts (MoE)',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Memory & Routing Architectures/Mixture of Experts.md',
    analogy: 'Information enters at input and ends at objective.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Feature vector , where is the feature dimension (e.g., OHLC, indicators).' },
      { id: 'experts', role: 'transform', label: 'Experts', detail: 'subnetworks , each an MLP or CNN, producing outputs .' },
      { id: 'gating_network', role: 'transform', label: 'Gating Network', detail: 'Computes weights for each expert' },
      { id: 'output', role: 'output', label: 'Output', detail: 'Weighted combination of expert outputs' },
      { id: 'sparse_gating', role: 'transform', label: 'Sparse Gating', detail: 'Select top- experts (e.g., ) to reduce computation' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize task-specific loss (e.g., MSE for regression)' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Expert Specialization', detail: 'Employs multiple subnetworks (experts), each specializing in different aspects of the data (e.g., market volatility, trends).' },
      { id: 'b2', at: 'experts', label: 'Gating Mechanism', detail: 'Uses a learnable gating network to assign weights to experts, routing inputs to the most relevant ones.' },
      { id: 'b3', at: 'input', label: 'Sparse Activation', detail: 'Activates only a subset of experts per input, reducing computational cost compared to dense networks.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'moe-composite',
    name: 'Mixture of Experts (Composite)',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Memory & Routing Architectures/Mixture of Experts.md',
    analogy: 'Information enters at input and ends at objective.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Feature vector , where is the feature dimension (e.g., OHLC, indicators).' },
      { id: 'experts', role: 'transform', label: 'Experts', detail: 'subnetworks , each an MLP or CNN, producing outputs .' },
      { id: 'gating_network', role: 'transform', label: 'Gating Network', detail: 'Computes weights for each expert' },
      { id: 'output', role: 'output', label: 'Output', detail: 'Weighted combination of expert outputs' },
      { id: 'sparse_gating', role: 'transform', label: 'Sparse Gating', detail: 'Select top- experts (e.g., ) to reduce computation' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize task-specific loss (e.g., MSE for regression)' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Expert Specialization', detail: 'Employs multiple subnetworks (experts), each specializing in different aspects of the data (e.g., market volatility, trends).' },
      { id: 'b2', at: 'experts', label: 'Gating Mechanism', detail: 'Uses a learnable gating network to assign weights to experts, routing inputs to the most relevant ones.' },
      { id: 'b3', at: 'input', label: 'Sparse Activation', detail: 'Activates only a subset of experts per input, reducing computational cost compared to dense networks.' },
    ],
    repoRunner: { templateId: 'composite_moe', note: 'Trained here through the generic composite_moe template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'stacking-composite',
    name: 'Stacking Ensemble (Composite)',
    archetype: 'ensemble-route',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Classical Hybrids/Stacked Ensemble Model.md',
    analogy: 'Information enters at level-0 (base models) and ends at support vector machines.',
    stages: [
      { id: 'level_0_base_models', role: 'transform', label: 'Level-0 (Base Models)', detail: 'A set of heterogeneous models, such as' },
      { id: 'decision_trees_random_fore', role: 'transform', label: 'Decision Trees, Random Forests' },
      { id: 'gradient_boosting_e_g_xgbo', role: 'update', label: 'Gradient Boosting (e.g., XGBoost, LightGBM)' },
      { id: 'neural_networks_e_g_mlps_c', role: 'transform', label: 'Neural Networks (e.g., MLPs, CNNs)' },
      { id: 'linear_models_e_g_logistic', role: 'transform', label: 'Linear Models (e.g., logistic regression)' },
      { id: 'support_vector_machines', role: 'transform', label: 'Support Vector Machines' },
    ],
    beats: [
      { id: 'b1', at: 'linear_models_e_g_logistic', label: 'Level-0 (Base Models)', detail: 'A set of heterogeneous models, such as' },
      { id: 'b2', at: 'decision_trees_random_fore', label: 'Decision Trees, Random Forests', detail: 'Decision Trees, Random Forests' },
      { id: 'b3', at: 'level_0_base_models', label: 'Gradient Boosting (e.g., XGBoost, LightGBM)', detail: 'Gradient Boosting (e.g., XGBoost, LightGBM)' },
    ],
    repoRunner: { templateId: 'composite_stacking', note: 'Trained here through the generic composite_stacking template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
];
