/**
 * feedforward-stack family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const FEEDFORWARD_STACK_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'rnn-cnn-hybrid',
    name: 'RNN-CNN Hybrid',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Classical Hybrids/RNN-CNN Hybrid.md',
    analogy: 'Information enters at cnn module and ends at parallel.',
    stages: [
      { id: 'cnn_module', role: 'transform', label: 'CNN Module', detail: 'Extracts spatial features using convolutional layers, often with pooling (e.g., max-pooling) to reduce dimensi' },
      { id: 'rnn_module', role: 'transform', label: 'RNN Module', detail: 'Processes the sequence of CNN-extracted features using RNN variants like LSTM or GRU to capture temporal dynam' },
      { id: 'fusion_layer', role: 'transform', label: 'Fusion Layer', detail: 'Combines CNN and RNN outputs, often via concatenation, attention, or dense layers.' },
      { id: 'output_layer', role: 'output', label: 'Output Layer', detail: 'Produces task-specific outputs (e.g., class probabilities, regression values).' },
      { id: 'sequential', role: 'transform', label: 'Sequential', detail: 'CNN processes each time step’s input, and RNN aggregates features over time (e.g., ConvLSTM).' },
      { id: 'parallel', role: 'transform', label: 'Parallel', detail: 'CNN and RNN process different input modalities, with outputs fused later.' },
    ],
    beats: [
      { id: 'b1', at: 'rnn_module', label: 'CNN Module', detail: 'Extracts spatial features using convolutional layers, often with pooling (e.g., max-pooling) to reduce dimensionality. For example, a VGG-like or ResNet-like backbone for images.' },
      { id: 'b2', at: 'cnn_module', label: 'RNN Module', detail: 'Processes the sequence of CNN-extracted features using RNN variants like LSTM or GRU to capture temporal dynamics.' },
      { id: 'b3', at: 'sequential', label: 'Fusion Layer', detail: 'Combines CNN and RNN outputs, often via concatenation, attention, or dense layers.' },
    ],
    repoRunner: { templateId: 'pytorch_cnn', note: 'Trained here through the generic pytorch_cnn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'convolutional-neural-network-cnn',
    name: 'Convolutional Neural Network (CNN)',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Convolutional Networks/Convolutional Neural Network (CNN).md',
    analogy: 'Information enters at input and ends at fully connected layer.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Grid-like data (e.g., candlestick chart) or (time-series), where are image dimensions, is channels, is time st' },
      { id: 'convolutional_layer', role: 'transform', label: 'Convolutional Layer', detail: 'Applies filters to produce feature maps' },
      { id: 'filter_size', role: 'transform', label: 'Filter size,', detail: 'Bias.' },
      { id: 'activation', role: 'transform', label: 'Activation', detail: 'Applies non-linearity (e.g., ).' },
      { id: 'pooling_layer', role: 'transform', label: 'Pooling Layer', detail: 'Reduces dimensions (e.g., max-pooling: ).' },
      { id: 'fully_connected_layer', role: 'transform', label: 'Fully Connected Layer', detail: 'Flattens feature maps and applies dense layers for task-specific outputs (e.g., price prediction, buy/sell sig' },
    ],
    beats: [
      { id: 'b1', at: 'input', label: 'Convolutional Layers', detail: 'Apply learnable filters to extract local features (e.g., candlestick patterns, price trends) from input data.' },
      { id: 'b2', at: 'pooling_layer', label: 'Pooling Layers', detail: 'Reduce spatial or temporal dimensions while preserving important features, enhancing computational efficiency and robustness.' },
      { id: 'b3', at: 'activation', label: 'Hierarchical Feature Learning', detail: 'Progressively learns low-level (e.g., edges) to high-level features (e.g., complex patterns) through stacked layers.' },
    ],
    repoRunner: { templateId: 'pytorch_cnn', note: 'Trained here through the generic pytorch_cnn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'densenet-densely-connected-cnn',
    name: 'DenseNet (Densely Connected CNN)',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Convolutional Networks/DenseNet (Densely Connected CNN).md',
    analogy: 'Information enters at input and ends at 1x1 convolution to reduce channels.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Grid-like data (e.g., candlestick chart) or (time-series), where are image dimensions, is channels, is time st' },
      { id: 'dense_block', role: 'transform', label: 'Dense Block', detail: 'A block of layers, where each layer receives feature maps from all previous layers' },
      { id: 'concatenation_of_feature_m', role: 'transform', label: 'Concatenation of feature maps' },
      { id: 'output', role: 'output', label: 'Output', detail: 'new feature maps per layer (growth rate).' },
      { id: 'transition_layer', role: 'transform', label: 'Transition Layer', detail: 'Reduces dimensions between dense blocks' },
      { id: '1x1_convolution_to_reduce_', role: 'transform', label: '1x1 convolution to reduce channels' },
    ],
    beats: [
      { id: 'b1', at: 'transition_layer', label: 'Dense Connectivity', detail: 'Each layer receives inputs from all preceding layers, concatenating feature maps to enhance information flow.' },
      { id: 'b2', at: '1x1_convolution_to_reduce_', label: 'Feature Reuse', detail: 'Reuses features across layers, reducing redundancy and improving computational efficiency.' },
      { id: 'b3', at: 'input', label: 'Bottleneck Layers', detail: 'Uses 1x1 convolutions to reduce dimensionality before dense connections, controlling model complexity.' },
    ],
    repoRunner: { templateId: 'pytorch_cnn', note: 'Trained here through the generic pytorch_cnn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'residual-neural-network-resnet',
    name: 'Residual Neural Network (ResNet)',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Convolutional Networks/Residual Neural Network (ResNet).md',
    analogy: 'Information enters at input and ends at architecture.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Grid-like data (e.g., candlestick chart) or (time-series), where are image dimensions, is channels, is time st' },
      { id: 'residual_block', role: 'transform', label: 'Residual Block' },
      { id: 'output', role: 'output', label: 'Output', detail: ', where is a sequence of convolutions, batch normalization, and ReLU' },
      { id: 'convolutional_weights_bn', role: 'transform', label: 'Convolutional weights, BN', detail: 'Batch normalization.' },
      { id: 'if_dimensions_mismatch_app', role: 'transform', label: 'If dimensions mismatch, apply a 1x1 convolution to for ali' },
      { id: 'architecture', role: 'transform', label: 'Architecture', detail: 'Stack of residual blocks, grouped into stages with increasing filter counts (e.g., 64, 128, 256, 512).' },
    ],
    beats: [
      { id: 'b1', at: 'architecture', label: 'Residual Connections', detail: 'Each layer learns a residual function such that the output is , allowing layers to learn identity functions if needed, easing optimization.' },
      { id: 'b2', at: 'input', label: 'Deep Architectures', detail: 'Enables training of very deep networks (e.g., 50-150 layers) without performance degradation.' },
      { id: 'b3', at: 'residual_block', label: 'Convolutional Layers', detail: 'Extracts local features (e.g., candlestick patterns, price trends) using convolutional filters.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'feedforward-neural-network-fnn',
    name: 'Feedforward Neural Network (FNN)',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Feedforward & MLPs/Feedforward Neural Network (FNN).md',
    analogy: 'Information enters at input and ends at linear for regression, softmax for classification.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Feature vector , where is the number of features (e.g., OHLC, indicators).' },
      { id: 'hidden_layer', role: 'transform', label: 'Hidden Layer', detail: 'For layer , compute' },
      { id: 'weight_matrix', role: 'transform', label: 'Weight matrix,', detail: 'Bias vector.' },
      { id: 'activation_function_e_g', role: 'transform', label: 'Activation function (e.g., )' },
      { id: 'output_layer', role: 'output', label: 'Output Layer', detail: 'Compute final output' },
      { id: 'linear_for_regression_soft', role: 'score', label: 'Linear for regression, softmax for classification' },
    ],
    beats: [
      { id: 'b1', at: 'hidden_layer', label: 'Layered Architecture', detail: 'Consists of an input layer, one or more hidden layers, and an output layer, with each layer containing nodes (neurons).' },
      { id: 'b2', at: 'linear_for_regression_soft', label: 'Fully Connected Layers', detail: 'Each neuron in a layer connects to every neuron in the next layer, weighted by learnable parameters.' },
      { id: 'b3', at: 'input', label: 'Non-Linear Activation', detail: 'Applies functions (e.g., ReLU, sigmoid) to capture complex market patterns.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'multilayer-perceptron-mlp',
    name: 'Multilayer Perceptron (MLP)',
    archetype: 'feedforward-stack',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Feedforward & MLPs/Multilayer Perceptron (MLP).md',
    analogy: 'Information enters at input and ends at linear for regression, softmax for classification.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Feature vector , where is the number of features (e.g., OHLC, indicators).' },
      { id: 'hidden_layer', role: 'transform', label: 'Hidden Layer', detail: 'For layer , compute' },
      { id: 'weight_matrix', role: 'transform', label: 'Weight matrix,', detail: 'Bias vector.' },
      { id: 'activation_function_e_g_or', role: 'transform', label: 'Activation function (e.g., or )' },
      { id: 'output_layer', role: 'output', label: 'Output Layer', detail: 'Compute final output' },
      { id: 'linear_for_regression_soft', role: 'score', label: 'Linear for regression, softmax for classification' },
    ],
    beats: [
      { id: 'b1', at: 'hidden_layer', label: 'Layered Structure', detail: 'Comprises an input layer, one or more hidden layers with neurons, and an output layer, enabling hierarchical feature learning.' },
      { id: 'b2', at: 'linear_for_regression_soft', label: 'Fully Connected Layers', detail: 'Each neuron connects to all neurons in the next layer, weighted by learnable parameters.' },
      { id: 'b3', at: 'input', label: 'Non-Linear Activation', detail: 'Uses functions (e.g., ReLU, sigmoid, tanh) to model non-linear market dynamics.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
];
