/**
 * graph-message-pass family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const GRAPH_MESSAGE_PASS_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'gnn-reinforcement-learner',
    name: 'GNN + Reinforcement Learner Hybrid',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Graph & Attention Hybrids/GNN + Reinforcement Learner.md',
    analogy: 'Information enters at gnn module and ends at policy network.',
    stages: [
      { id: 'gnn_module', role: 'transform', label: 'GNN Module' },
      { id: 'input', role: 'input', label: 'Input', detail: 'Graph \\( G \\) with node features (e.g., asset prices) and edges (e.g., correlations).' },
      { id: 'layers', role: 'transform', label: 'Layers', detail: 'GCN, GAT, or GraphSAGE for message passing.' },
      { id: 'output', role: 'output', label: 'Output', detail: 'Node embeddings or pooled graph embedding as RL state \\( s \\).' },
      { id: 'rl_module', role: 'transform', label: 'RL Module' },
      { id: 'policy_network', role: 'transform', label: 'Policy Network', detail: 'Maps state \\( s \\) to action probabilities \\( \\pi(a|s) \\), often an MLP.' },
    ],
    beats: [
      { id: 'b1', at: 'policy_network', label: 'GNN Module', detail: 'GNN Module' },
      { id: 'b2', at: 'input', label: 'Input', detail: 'Graph \\( G \\) with node features (e.g., asset prices) and edges (e.g., correlations).' },
      { id: 'b3', at: 'layers', label: 'Layers', detail: 'GCN, GAT, or GraphSAGE for message passing.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'masked-graph-modeling',
    name: 'Masked Graph Modeling',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Machine Learning/Self-Supervised Learning/Masked Modeling/Masked Graph Modeling.md',
    analogy: 'Information enters at only processes visible nodes/edges for efficiency and ends at masking module.',
    stages: [
      { id: 'only_processes_visible_nod', role: 'transform', label: 'Only processes visible nodes/edges for efficiency' },
      { id: 'output', role: 'output', label: 'Output', detail: 'Latent node or graph embeddings \\( H \\).' },
      { id: 'lightweight_gnn_or_mlp_rec', role: 'output', label: 'Lightweight GNN or MLP reconstructing masked elements' },
      { id: 'node_prediction', role: 'output', label: 'Node prediction', detail: 'Maps \\( H_v \\) to feature space.' },
      { id: 'edge_prediction', role: 'output', label: 'Edge prediction', detail: 'Computes edge probabilities via dot products or MLPs.' },
      { id: 'masking_module', role: 'transform', label: 'Masking Module' },
    ],
    beats: [
      { id: 'b1', at: 'edge_prediction', label: 'Only processes visible nodes/edges for efficiency', detail: 'Only processes visible nodes/edges for efficiency' },
      { id: 'b2', at: 'lightweight_gnn_or_mlp_rec', label: 'Output', detail: 'Latent node or graph embeddings \\( H \\).' },
      { id: 'b3', at: 'masking_module', label: 'Lightweight GNN or MLP reconstructing masked element', detail: 'Lightweight GNN or MLP reconstructing masked elements' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'graph-based-semi-supervised-learning',
    name: 'Graph-Based Semi-Supervised Learning',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Machine Learning/Semi-Supervised Learning/Graph-Based Methods/Graph-Based Semi-Supervised Learning.md',
    analogy: 'Information enters at label propagation (lp) and ends at equivalent to lp but provides probabilistic interpretations.',
    stages: [
      { id: 'label_propagation_lp', role: 'update', label: 'Label Propagation (LP)' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize , where is edge weight, and is the predicted label.' },
      { id: 'label_spreading_ls', role: 'transform', label: 'Label Spreading (LS)' },
      { id: 'more_robust_to_noisy_label', role: 'transform', label: 'More robust to noisy labels than LP' },
      { id: 'gaussian_random_fields_grf', role: 'transform', label: 'Gaussian Random Fields (GRF)' },
      { id: 'equivalent_to_lp_but_provi', role: 'transform', label: 'Equivalent to LP but provides probabilistic interpretation' },
    ],
    beats: [
      { id: 'b1', at: 'more_robust_to_noisy_label', label: 'Graph Representation', detail: 'Data points are nodes in a graph, with edges weighted by similarity (e.g., based on Euclidean distance or correlation).' },
      { id: 'b2', at: 'objective', label: 'Label Propagation', detail: 'Labels from labeled nodes are propagated to unlabeled nodes via graph edges, assuming smoothness (nearby nodes share similar labels).' },
      { id: 'b3', at: 'label_spreading_ls', label: 'Manifold Assumption', detail: 'Data lies on a low-dimensional manifold, where graph connectivity reflects underlying structure.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'label-propagation',
    name: 'Label Propagation',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Machine Learning/Semi-Supervised Learning/Graph-Based Methods/Label Propagation.md',
    analogy: 'Information enters at graph construction and ends at for unlabeled points, initialize.',
    stages: [
      { id: 'graph_construction', role: 'transform', label: 'Graph Construction' },
      { id: 'nodes_represent_data_point', role: 'transform', label: 'Nodes represent data points (e.g., OHLC sequences)' },
      { id: 'form_a_weight_matrix_and_c', role: 'transform', label: 'Form a weight matrix and compute the degree matrix , where' },
      { id: 'normalize_to_obtain_the_tr', role: 'transform', label: 'Normalize to obtain the transition matrix ' },
      { id: 'label_initialization', role: 'transform', label: 'Label Initialization' },
      { id: 'for_unlabeled_points_initi', role: 'transform', label: 'For unlabeled points, initialize ' },
    ],
    beats: [
      { id: 'b1', at: 'form_a_weight_matrix_and_c', label: 'Graph-Based Representation', detail: 'Data points are nodes in a graph, with edges weighted by similarity (e.g., based on distance or correlation).' },
      { id: 'b2', at: 'label_initialization', label: 'Smoothness Assumption', detail: 'Labels vary smoothly over the graph, so connected nodes tend to share the same label.' },
      { id: 'b3', at: 'graph_construction', label: 'Iterative Propagation', detail: 'Labels are propagated iteratively from labeled to unlabeled nodes via edge weights, converging to a harmonic solution.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'label-spreading',
    name: 'Label Spreading',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Machine Learning/Semi-Supervised Learning/Graph-Based Methods/Label Spreading.md',
    analogy: 'Information enters at graph construction and ends at for unlabeled points, initialize.',
    stages: [
      { id: 'graph_construction', role: 'transform', label: 'Graph Construction' },
      { id: 'nodes_represent_data_point', role: 'transform', label: 'Nodes represent data points (e.g., OHLC sequences)' },
      { id: 'form_a_weight_matrix_and_d', role: 'transform', label: 'Form a weight matrix and degree matrix , where ' },
      { id: 'compute_the_normalized_lap', role: 'transform', label: 'Compute the normalized Laplacian', detail: '.' },
      { id: 'label_initialization', role: 'transform', label: 'Label Initialization' },
      { id: 'for_unlabeled_points_initi', role: 'transform', label: 'For unlabeled points, initialize ' },
    ],
    beats: [
      { id: 'b1', at: 'label_initialization', label: 'Graph-Based Representation', detail: 'Data points are nodes in a graph, with edges weighted by similarity (e.g., distance or correlation).' },
      { id: 'b2', at: 'compute_the_normalized_lap', label: 'Smoothness Assumption', detail: 'Labels vary smoothly over the graph, so connected nodes tend to share similar labels.' },
      { id: 'b3', at: 'graph_construction', label: 'Regularization', detail: 'Penalizes deviations from initial labels to mitigate noise and overfitting, unlike LP’s strict clamping of labeled nodes.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'manifold-regularization',
    name: 'Manifold Regularization',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Machine Learning/Semi-Supervised Learning/Graph-Based Methods/Manifold Regularization.md',
    analogy: 'Information enters at laplacian regularized least squares (laprls) and ends at graph neural network (gnn)-based mr.',
    stages: [
      { id: 'laplacian_regularized_leas', role: 'loss', label: 'Laplacian Regularized Least Squares (LapRLS)' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize supervised loss plus .' },
      { id: 'laplacian_support_vector_m', role: 'transform', label: 'Laplacian Support Vector Machines (LapSVM)' },
      { id: 'manifold_regularized_neura', role: 'loss', label: 'Manifold Regularized Neural Networks' },
      { id: 'transductive_mr', role: 'transform', label: 'Transductive MR' },
      { id: 'graph_neural_network_gnn_b', role: 'transform', label: 'Graph Neural Network (GNN)-Based MR' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Manifold Assumption', detail: 'Data points lie on a low-dimensional manifold embedded in a high-dimensional space, and labels should be smooth along this manifold.' },
      { id: 'b2', at: 'transductive_mr', label: 'Graph-Based Geometry', detail: 'A graph represents data points as nodes and their similarities as edges, approximating the manifold’s structure.' },
      { id: 'b3', at: 'laplacian_support_vector_m', label: 'Regularization', detail: 'Combines a supervised loss for labeled data with a graph-based smoothness penalty for all data.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'graph-convolutional-network-gcn',
    name: 'Graph Convolutional Network (GCN)',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Graph Neural Networks/Graph Convolutional Network (GCN).md',
    analogy: 'Information enters at input and ends at learnable weight matrix.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Graph with node features , where is feature dimension, and adjacency matrix .' },
      { id: 'layer_propagation', role: 'update', label: 'Layer Propagation', detail: 'For layer , update node features' },
      { id: 'adjacency_matrix_with_self', role: 'transform', label: 'Adjacency matrix with self-loops' },
      { id: 'degree_matrix', role: 'transform', label: 'Degree matrix, ' },
      { id: 'node_features_at_layer', role: 'transform', label: 'Node features at layer , ' },
      { id: 'learnable_weight_matrix', role: 'transform', label: 'Learnable weight matrix' },
    ],
    beats: [
      { id: 'b1', at: 'layer_propagation', label: 'Graph Representation', detail: 'Models data as a graph , where are nodes (e.g., currency pairs, time steps) and are edges (e.g., correlations, temporal links).' },
      { id: 'b2', at: 'input', label: 'Feature Aggregation', detail: 'Updates node features by aggregating information from neighbors using a normalized adjacency matrix, capturing local graph structure.' },
      { id: 'b3', at: 'adjacency_matrix_with_self', label: 'Convolutional Layers', detail: 'Applies learnable linear transformations to aggregated features, analogous to CNN convolutions.' },
    ],
    repoRunner: { templateId: 'pytorch_cnn', note: 'Trained here through the generic pytorch_cnn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'graph-neural-network-gnn',
    name: 'Graph Neural Network (GNN)',
    archetype: 'graph-message-pass',
    provenance: 'schematic',
    specPath: 'Neural Network Architectures/Graph Neural Networks/Graph Neural Network (GNN).md',
    analogy: 'Information enters at input and ends at learnable weight matrix.',
    stages: [
      { id: 'input', role: 'input', label: 'Input', detail: 'Graph with node features , where is feature dimension, and adjacency matrix .' },
      { id: 'message_passing', role: 'transform', label: 'Message Passing', detail: 'For node at layer' },
      { id: 'node_s_features_at_layer', role: 'transform', label: 'Node ’s features at layer , ' },
      { id: 'neighbors_of_node', role: 'transform', label: 'Neighbors of node ' },
      { id: 'aggregation_function_e_g_m', role: 'transform', label: 'Aggregation function (e.g., mean, sum, max)' },
      { id: 'learnable_weight_matrix', role: 'transform', label: 'Learnable weight matrix' },
    ],
    beats: [
      { id: 'b1', at: 'neighbors_of_node', label: 'Graph Representation', detail: 'Models data as a graph , where are nodes (e.g., currency pairs, time steps) and are edges (e.g., correlations, temporal links).' },
      { id: 'b2', at: 'input', label: 'Message Passing', detail: 'Aggregates features from neighboring nodes to update each node’s representation, capturing local and global structures.' },
      { id: 'b3', at: 'message_passing', label: 'Learnable Aggregation', detail: 'Uses neural networks to learn how to combine neighbor information, enabling flexible modeling of relationships.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
];
