/**
 * projection-embed family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const PROJECTION_EMBED_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'independent-component-analysis-ica',
    name: 'Independent Component Analysis (ICA)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Dimensionality Reduction/Independent Component Analysis (ICA).md',
    analogy: 'Information enters at observed data and ends at training.',
    stages: [
      { id: 'observed_data', role: 'transform', label: 'Observed data', detail: ', where ( samples, features), is the mixing matrix, is the source matrix with independent components.' },
      { id: 'goal', role: 'transform', label: 'Goal', detail: 'Estimate the unmixing matrix such that .' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Maximize the independence of components in , measured by non-Gaussianity (e.g., negentropy: , where is a non-q' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector.' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of components , non-linearity function (e.g., logcosh, exp).' },
      { id: 'training', role: 'transform', label: 'Training' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Statistical Independence', detail: 'Assumes observed data is a linear mixture of independent sources, aiming to recover these sources.' },
      { id: 'b2', at: 'training', label: 'Non-Gaussianity', detail: 'Maximizes the non-Gaussianity of components (e.g., via kurtosis or negentropy), as Gaussian signals are not uniquely separable.' },
      { id: 'b3', at: 'dataset', label: 'Linear Mixing', detail: 'Models data as , where is the observed data, is the mixing matrix, and is the matrix of independent components.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'non-negative-matrix-factorization-nmf',
    name: 'Non-Negative Matrix Factorization (NMF)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Dimensionality Reduction/Non-Negative Matrix Factorization (NMF).md',
    analogy: 'Information enters at data matrix and ends at hyperparameters.',
    stages: [
      { id: 'data_matrix', role: 'input', label: 'Data matrix', detail: ', where is samples, is features.' },
      { id: 'factorization', role: 'transform', label: 'Factorization', detail: ', where (basis matrix), (coefficient matrix), is the number of components.' },
      { id: 'objective_function_frobeni', role: 'loss', label: 'Objective function (Frobenius norm)' },
      { id: 'alternative', role: 'transform', label: 'Alternative', detail: 'Kullback-Leibler divergence for sparse data' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: '.' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of components , loss function, initialization method.' },
    ],
    beats: [
      { id: 'b1', at: 'alternative', label: 'Non-Negative Decomposition', detail: 'Approximates a data matrix as , where and are non-negative matrices representing basis vectors and coefficients.' },
      { id: 'b2', at: 'dataset', label: 'Latent Features', detail: 'Identifies additive components that capture underlying patterns in the data.' },
      { id: 'b3', at: 'objective_function_frobeni', label: 'Additive Structure', detail: 'Ensures components are combined linearly with positive weights, enhancing interpretability.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'principal-component-analysis-pca',
    name: 'Principal Component Analysis (PCA)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Dimensionality Reduction/Principal Component Analysis (PCA).md',
    analogy: 'Information enters at data matrix and ends at training.',
    stages: [
      { id: 'data_matrix', role: 'input', label: 'Data matrix', detail: ', where is samples, is features.' },
      { id: 'goal', role: 'transform', label: 'Goal', detail: 'Find principal components and scores such that , where is the mean vector.' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Maximize variance of projected data, equivalent to minimizing reconstruction error' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector.' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of components , standardization method.' },
      { id: 'training', role: 'transform', label: 'Training' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Variance Maximization', detail: 'Identifies orthogonal principal components that capture the maximum variance in the data.' },
      { id: 'b2', at: 'training', label: 'Linear Transformation', detail: 'Projects data onto a new coordinate system defined by principal components (eigenvectors of the covariance matrix).' },
      { id: 'b3', at: 'dataset', label: 'Dimensionality Reduction', detail: 'Retains the top components to reduce data dimensions while preserving most information.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'manifold-learning-isomap-lle',
    name: 'Manifold Learning (Isomap, LLE)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Manifold Learning/Manifold Learning (Isomap, LLE).md',
    analogy: 'Information enters at non-linear dimensionality reduction and ends at no labels required.',
    stages: [
      { id: 'non_linear_dimensionality_', role: 'transform', label: 'Non-Linear Dimensionality Reduction', detail: 'Assumes data lies on a low-dimensional manifold embedded in high-dimensional space, unlike PCA’s linear assump' },
      { id: 'isomap', role: 'transform', label: 'Isomap', detail: 'Preserves geodesic distances (shortest paths on the manifold) using a graph-based approach, capturing global s' },
      { id: 'lle', role: 'transform', label: 'LLE', detail: 'Preserves local geometry by modeling each point as a linear combination of its neighbors, focusing on local st' },
      { id: 'low_dimensional_embedding', role: 'latent', label: 'Low-Dimensional Embedding', detail: 'Projects data into a lower-dimensional space (e.g., 2D or 3D) for analysis or downstream tasks.' },
      { id: 'no_labels_required', role: 'transform', label: 'No Labels Required', detail: 'Fully unsupervised, suitable for unlabeled Forex data.' },
    ],
    beats: [
      { id: 'b1', at: 'no_labels_required', label: 'Non-Linear Dimensionality Reduction', detail: 'Assumes data lies on a low-dimensional manifold embedded in high-dimensional space, unlike PCA’s linear assumption.' },
      { id: 'b2', at: 'isomap', label: 'Isomap', detail: 'Preserves geodesic distances (shortest paths on the manifold) using a graph-based approach, capturing global structure.' },
      { id: 'b3', at: 'low_dimensional_embedding', label: 'LLE', detail: 'Preserves local geometry by modeling each point as a linear combination of its neighbors, focusing on local structure.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 't-sne-t-distributed-stochastic-neighbor-embedding',
    name: 't-Distributed Stochastic Neighbor Embedding (t-SNE)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Manifold Learning/t-SNE (t-Distributed Stochastic Neighbor Embedding).md',
    analogy: 'Information enters at high-dimensional similarities and ends at dataset.',
    stages: [
      { id: 'high_dimensional_similarit', role: 'score', label: 'High-Dimensional Similarities', detail: 'For points , compute conditional probability' },
      { id: 'bandwidth_set_via_perplexi', role: 'transform', label: 'Bandwidth, set via perplexity (e.g., 5-50)' },
      { id: 'symmetric_probability', role: 'score', label: 'Symmetric probability', detail: '.' },
      { id: 'low_dimensional_similariti', role: 'score', label: 'Low-Dimensional Similarities', detail: 'For embedded points , use t-distribution' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize Kullback-Leibler (KL) divergence between and' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where .' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Local Structure Preservation', detail: 'Captures local similarities by modeling high-dimensional data points as conditional probabilities, preserving neighborhood relationships in low-dimensional space.' },
      { id: 'b2', at: 'dataset', label: 'Probability-Based Embedding', detail: 'Uses Gaussian distributions in high-dimensional space and t-distributions in low-dimensional space to compute similarities.' },
      { id: 'b3', at: 'low_dimensional_similariti', label: 'Non-Linear Reduction', detail: 'Handles complex, non-linear manifolds, unlike PCA’s linear approach.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'umap-uniform-manifold-approximation-and-projection',
    name: 'Uniform Manifold Approximation and Projection (UMAP)',
    archetype: 'projection-embed',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Manifold Learning/UMAP (Uniform Manifold Approximation and Projection).md',
    analogy: 'Information enters at high-dimensional representation and ends at objective.',
    stages: [
      { id: 'high_dimensional_represent', role: 'latent', label: 'High-Dimensional Representation', detail: 'Constructs a weighted graph where edge weights represent local similarities' },
      { id: 'distance_to_nearest_neighb', role: 'score', label: 'Distance to nearest neighbor,', detail: 'Normalizes weights based on local connectivity (set via n_neighbors).' },
      { id: 'forms_a_fuzzy_simplicial_s', role: 'transform', label: 'Forms a fuzzy simplicial set from the graph' },
      { id: 'low_dimensional_representa', role: 'latent', label: 'Low-Dimensional Representation', detail: 'Defines a similar fuzzy set in the low-dimensional space' },
      { id: 'parameters_controlling_emb', role: 'latent', label: 'Parameters controlling embedding shape (learned or fixed)' },
      { id: 'objective', role: 'loss', label: 'Objective', detail: 'Minimize cross-entropy between and' },
    ],
    beats: [
      { id: 'b1', at: 'objective', label: 'Topological Structure Preservation', detail: 'Models data as a topological manifold, preserving local neighborhoods and global relationships in the low-dimensional embedding.' },
      { id: 'b2', at: 'low_dimensional_representa', label: 'Riemannian Geometry', detail: 'Constructs a fuzzy simplicial complex to approximate the manifold, optimizing the embedding to match high-dimensional topology.' },
      { id: 'b3', at: 'distance_to_nearest_neighb', label: 'Cross-Entropy Optimization', detail: 'Minimizes the difference between high- and low-dimensional fuzzy sets using a cross-entropy loss.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
];
