/**
 * symbolic-hybrid family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const SYMBOLIC_HYBRID_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'bayesian-neural-hybrid-model',
    name: 'Bayesian-Neural Hybrid Model',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Generative-Discriminative Hybrids/Bayesian-Neural Hybrid Model.md',
    analogy: 'Information enters at neural network backbone and ends at bayesian weight distributions.',
    stages: [
      { id: 'neural_network_backbone', role: 'transform', label: 'Neural Network Backbone', detail: 'A standard neural network (e.g., MLP, CNN, RNN) with weights modeled as distributions. Common choices' },
      { id: 'fully_connected_layers_for', role: 'transform', label: 'Fully connected layers for tabular data' },
      { id: 'convolutional_layers_for_i', role: 'transform', label: 'Convolutional layers for images' },
      { id: 'recurrent_layers_for_time_', role: 'transform', label: 'Recurrent layers for time-series (e.g., forex data)' },
      { id: 'probabilistic_layers', role: 'transform', label: 'Probabilistic Layers', detail: 'Output distributions (e.g., Gaussian for regression, categorical for classification) to model aleatoric uncert' },
      { id: 'bayesian_weight_distributi', role: 'transform', label: 'Bayesian Weight Distributions', detail: 'Weights are parameterized by mean and variance (e.g., \\( w \\sim \\mathcal{N}(\\mu, \\sigma^2) \\)).' },
    ],
    beats: [
      { id: 'b1', at: 'convolutional_layers_for_i', label: 'Neural Network Backbone', detail: 'A standard neural network (e.g., MLP, CNN, RNN) with weights modeled as distributions. Common choices' },
      { id: 'b2', at: 'bayesian_weight_distributi', label: 'Fully connected layers for tabular data', detail: 'Fully connected layers for tabular data' },
      { id: 'b3', at: 'fully_connected_layers_for', label: 'Convolutional layers for images', detail: 'Convolutional layers for images' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'differentiable-logic-layer',
    name: 'Differentiable Logic Layer',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Differentiable Logic Layer.md',
    analogy: 'Information enters at neural backbone and ends at quantifier handling.',
    stages: [
      { id: 'neural_backbone', role: 'transform', label: 'Neural Backbone' },
      { id: 'outputs_feature_embeddings', role: 'latent', label: 'Outputs feature embeddings \\( h \\)' },
      { id: 'differentiable_logic_layer', role: 'transform', label: 'Differentiable Logic Layer' },
      { id: 'logical_operations', role: 'transform', label: 'Logical Operations', detail: 'Implements AND, OR, NOT using t-norms or soft approximations.' },
      { id: 'rule_encoding', role: 'transform', label: 'Rule Encoding', detail: 'Represents rules as weighted combinations or neural functions.' },
      { id: 'quantifier_handling', role: 'transform', label: 'Quantifier Handling', detail: 'Aggregates over instances (e.g., min/max).' },
    ],
    beats: [
      { id: 'b1', at: 'differentiable_logic_layer', label: 'Neural Backbone', detail: 'Neural Backbone' },
      { id: 'b2', at: 'neural_backbone', label: 'Outputs feature embeddings \\( h \\)', detail: 'Outputs feature embeddings \\( h \\)' },
      { id: 'b3', at: 'logical_operations', label: 'Differentiable Logic Layer', detail: 'Differentiable Logic Layer' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'meta-learned-symbolic-router',
    name: 'Meta-Learned Symbolic Router',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Meta-Learned Symbolic Router.md',
    analogy: 'Information enters at neural feature extractor and ends at predefined or learned rules (e.g., "buy if rsi > 70").',
    stages: [
      { id: 'neural_feature_extractor', role: 'transform', label: 'Neural Feature Extractor' },
      { id: 'outputs_feature_embeddings', role: 'latent', label: 'Outputs feature embeddings \\( h \\)' },
      { id: 'meta_learned_router', role: 'transform', label: 'Meta-Learned Router' },
      { id: 'often_uses_softmax_to_ensu', role: 'transform', label: 'Often uses softmax to ensure \\( \\sum w_k = 1 \\)' },
      { id: 'symbolic_rule_set', role: 'transform', label: 'Symbolic Rule Set' },
      { id: 'predefined_or_learned_rule', role: 'transform', label: 'Predefined or learned rules (e.g., "buy if RSI > 70")' },
    ],
    beats: [
      { id: 'b1', at: 'often_uses_softmax_to_ensu', label: 'Neural Feature Extractor', detail: 'Neural Feature Extractor' },
      { id: 'b2', at: 'predefined_or_learned_rule', label: 'Outputs feature embeddings \\( h \\)', detail: 'Outputs feature embeddings \\( h \\)' },
      { id: 'b3', at: 'symbolic_rule_set', label: 'Meta-Learned Router', detail: 'Meta-Learned Router' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'neuro-symbolic-model',
    name: 'Neuro-Symbolic Model',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Neuro-Symbolic Model.md',
    analogy: 'Information enters at neural backbone and ends at examples.',
    stages: [
      { id: 'neural_backbone', role: 'transform', label: 'Neural Backbone' },
      { id: 'outputs', role: 'output', label: 'Outputs', detail: 'Feature embeddings or task-specific predictions.' },
      { id: 'symbolic_layer', role: 'transform', label: 'Symbolic Layer' },
      { id: 'encodes_rules_as_different', role: 'transform', label: 'Encodes rules as differentiable functions or logic operati' },
      { id: 'handles_logical_constraint', role: 'transform', label: 'Handles logical constraints, quantifiers, or knowledge bas' },
      { id: 'examples', role: 'transform', label: 'Examples', detail: 'Logic Tensor Networks, differentiable ILP.' },
    ],
    beats: [
      { id: 'b1', at: 'encodes_rules_as_different', label: 'Neural Backbone', detail: 'Neural Backbone' },
      { id: 'b2', at: 'neural_backbone', label: 'Outputs', detail: 'Feature embeddings or task-specific predictions.' },
      { id: 'b3', at: 'handles_logical_constraint', label: 'Symbolic Layer', detail: 'Symbolic Layer' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'probabilistic-program-deepnet',
    name: 'Probabilistic Program + DeepNet',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Probabilistic Program + DeepNet.md',
    analogy: 'Information enters at deep neural network and ends at outputs.',
    stages: [
      { id: 'deep_neural_network', role: 'transform', label: 'Deep Neural Network' },
      { id: 'outputs', role: 'output', label: 'Outputs', detail: 'Feature embeddings \\( h \\), distribution parameters, or direct inputs to the program.' },
      { id: 'probabilistic_program', role: 'transform', label: 'Probabilistic Program' },
      { id: 'defines_stochastic_variabl', role: 'transform', label: 'Defines stochastic variables and logical rules' },
      { id: 'implemented_using_framewor', role: 'transform', label: 'Implemented using frameworks like Pyro, Stan, or DeepProbL' },
      { id: 'outputs_2', role: 'output', label: 'Outputs', detail: 'Probabilistic predictions or sampled outcomes.' },
    ],
    beats: [
      { id: 'b1', at: 'outputs', label: 'Deep Neural Network', detail: 'Deep Neural Network' },
      { id: 'b2', at: 'probabilistic_program', label: 'Outputs', detail: 'Feature embeddings \\( h \\), distribution parameters, or direct inputs to the program.' },
      { id: 'b3', at: 'implemented_using_framewor', label: 'Probabilistic Program', detail: 'Probabilistic Program' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'residual-learning-over-rules',
    name: 'Residual Learning over Rules',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Residual Learning over Rules.md',
    analogy: 'Information enters at symbolic rule module and ends at fusion layer.',
    stages: [
      { id: 'symbolic_rule_module', role: 'transform', label: 'Symbolic Rule Module' },
      { id: 'output', role: 'output', label: 'Output', detail: 'Rule-based predictions \\( r(x) \\).' },
      { id: 'neural_residual_module', role: 'transform', label: 'Neural Residual Module' },
      { id: 'input', role: 'input', label: 'Input', detail: 'Raw data \\( x \\) or features derived from it.' },
      { id: 'output_2', role: 'output', label: 'Output', detail: 'Residual correction \\( f_\\theta(x) \\).' },
      { id: 'fusion_layer', role: 'transform', label: 'Fusion Layer' },
    ],
    beats: [
      { id: 'b1', at: 'input', label: 'Symbolic Rule Module', detail: 'Symbolic Rule Module' },
      { id: 'b2', at: 'output_2', label: 'Output', detail: 'Rule-based predictions \\( r(x) \\).' },
      { id: 'b3', at: 'neural_residual_module', label: 'Neural Residual Module', detail: 'Neural Residual Module' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'rule-augmented-neural-net',
    name: 'Rule-Augmented Neural Net',
    archetype: 'symbolic-hybrid',
    provenance: 'schematic',
    specPath: 'Hybrid & Composite Architectures/Neuro-Symbolic Systems/Rule-Augmented Neural Net.md',
    analogy: 'Information enters at neural backbone and ends at threshold-based rules (e.g., "stop loss if price drops 5%").',
    stages: [
      { id: 'neural_backbone', role: 'transform', label: 'Neural Backbone' },
      { id: 'processes_inputs_using_mlp', role: 'transform', label: 'Processes inputs using MLPs, CNNs, LSTMs, or transformers' },
      { id: 'outputs', role: 'output', label: 'Outputs', detail: 'Feature embeddings \\( h \\) or initial predictions.' },
      { id: 'rule_augmentation_module', role: 'transform', label: 'Rule Augmentation Module' },
      { id: 'logical_rules_e_g_buy_if_r', role: 'transform', label: 'Logical rules (e.g., "buy if RSI > 70")' },
      { id: 'threshold_based_rules_e_g_', role: 'loss', label: 'Threshold-based rules (e.g., "stop loss if price drops 5%"' },
    ],
    beats: [
      { id: 'b1', at: 'rule_augmentation_module', label: 'Neural Backbone', detail: 'Neural Backbone' },
      { id: 'b2', at: 'neural_backbone', label: 'Processes inputs using MLPs, CNNs, LSTMs, or transfo', detail: 'Processes inputs using MLPs, CNNs, LSTMs, or transformers' },
      { id: 'b3', at: 'logical_rules_e_g_buy_if_r', label: 'Outputs', detail: 'Feature embeddings \\( h \\) or initial predictions.' },
    ],
    repoRunner: { templateId: 'pytorch_mlp', note: 'This repo has no runner for this architecture. Training this spec renders the generic pytorch_mlp template \u2014 a plain MLP over the 35-feature vector, with none of the mechanism shown above.' },
    kernelId: null,
    curation: 'extracted',
  },
];
