/**
 * tree-route family \u2014 EXTRACTED entries.
 *
 * Generated by scripts/build_mechanism_registry.py. Every stage and beat
 * below was lifted from the Principles / Algorithm section of the single
 * markdown spec named in each entry's `specPath`; nothing here is invented.
 * These carry `curation: 'extracted'` to distinguish them from the
 * hand-read entries, which carry 'curated'.
 *
 * Regenerate rather than hand-editing:
 *     uv run python scripts/build_mechanism_registry.py
 */

import type { MechanismSpec } from './types';

export const TREE_ROUTE_EXTRACTED: MechanismSpec[] = [
  {
    catalogKey: 'catboost',
    name: 'CatBoost',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Boosting Methods/CatBoost.md',
    analogy: 'Information enters at dataset and ends at iteration (for to ).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical and categorical features, is the target (classification or regression).' },
      { id: 'loss_function', role: 'loss', label: 'Loss function', detail: '(e.g., log loss for classification, MSE for regression).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of trees ( ), learning rate ( ), tree depth, etc.' },
      { id: 'initialization', role: 'input', label: 'Initialization' },
      { id: 'initialize_model_predictio', role: 'input', label: 'Initialize model prediction', detail: 'or a constant (e.g., mean target for regression).' },
      { id: 'iteration_for_to', role: 'transform', label: 'Iteration (for to )' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Gradient Boosting', detail: 'Sequentially builds decision trees, each correcting the residuals of the previous ensemble, minimizing a loss function via gradient descent.' },
      { id: 'b2', at: 'initialize_model_predictio', label: 'Categorical Feature Handling', detail: 'Automatically processes categorical features using target-based encoding, reducing preprocessing needs.' },
      { id: 'b3', at: 'loss_function', label: 'Ordered Boosting', detail: 'Mitigates overfitting by using ordered target statistics, ensuring unbiased gradient estimates.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'gradient-boosting-machine-gbm',
    name: 'Gradient Boosting Machine (GBM)',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Boosting Methods/Gradient Boosting Machine (GBM).md',
    analogy: 'Information enters at dataset and ends at iteration (for to ).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical/categorical features, is the target.' },
      { id: 'loss_function', role: 'loss', label: 'Loss function', detail: '(e.g., MSE, log loss).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of trees ( ), learning rate ( ), tree depth, subsampling rate.' },
      { id: 'initialization', role: 'input', label: 'Initialization' },
      { id: 'initialize_predictions', role: 'input', label: 'Initialize predictions', detail: '(e.g., mean for regression, log-odds for classification).' },
      { id: 'iteration_for_to', role: 'transform', label: 'Iteration (for to )' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Gradient Boosting', detail: 'Sequentially adds decision trees, each fitting the negative gradient (residuals) of the loss function, reducing prediction errors.' },
      { id: 'b2', at: 'loss_function', label: 'Additive Ensemble', detail: 'Combines weak learners (shallow trees) into a strong model: , where is the learning rate.' },
      { id: 'b3', at: 'iteration_for_to', label: 'Loss Minimization', detail: 'Optimizes a differentiable loss function (e.g., MSE for regression, log loss for classification).' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'lightgbm',
    name: 'LightGBM',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Boosting Methods/LightGBM.md',
    analogy: 'Information enters at dataset and ends at iteration (for to ).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical/categorical features, is the target.' },
      { id: 'loss_function', role: 'loss', label: 'Loss function', detail: '(e.g., MSE for regression, log loss for classification).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of trees ( ), learning rate ( ), max leaves, subsampling rates.' },
      { id: 'initialization', role: 'input', label: 'Initialization' },
      { id: 'initialize_predictions', role: 'input', label: 'Initialize predictions', detail: '(e.g., mean for regression).' },
      { id: 'iteration_for_to', role: 'transform', label: 'Iteration (for to )' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Gradient Boosting', detail: 'Sequentially builds decision trees, each correcting residuals of prior trees via gradient descent.' },
      { id: 'b2', at: 'loss_function', label: 'Histogram-Based Splitting', detail: 'Bins continuous features into discrete histograms, reducing memory and speeding up split finding.' },
      { id: 'b3', at: 'iteration_for_to', label: 'Leaf-Wise Growth', detail: 'Grows trees by splitting the leaf with the highest loss reduction, enabling deeper, more accurate models.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'xgboost',
    name: 'XGBoost',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Boosting Methods/XGBoost.md',
    analogy: 'Information enters at dataset and ends at iteration (for to ).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical/categorical features, is the target.' },
      { id: 'loss_function', role: 'loss', label: 'Loss function', detail: '(e.g., MSE for regression, log loss for classification).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of trees ( ), learning rate ( ), max depth, regularization terms.' },
      { id: 'initialization', role: 'input', label: 'Initialization' },
      { id: 'initialize_predictions', role: 'input', label: 'Initialize predictions', detail: 'or a constant (e.g., mean for regression).' },
      { id: 'iteration_for_to', role: 'transform', label: 'Iteration (for to )' },
    ],
    beats: [
      { id: 'b1', at: 'dataset', label: 'Gradient Boosting', detail: 'Sequentially adds decision trees, each fitting the negative gradient of the loss function to correct prior errors.' },
      { id: 'b2', at: 'loss_function', label: 'Regularized Objective', detail: 'Incorporates L1 and L2 penalties to prevent overfitting, balancing model complexity and accuracy.' },
      { id: 'b3', at: 'iteration_for_to', label: 'Level-Wise Growth', detail: 'Builds trees level by level, optimizing splits to maximize loss reduction.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'random-forest',
    name: 'Random Forest',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Ensemble Methods/Random Forest.md',
    analogy: 'Information enters at dataset and ends at sample a bootstrap subset from with replacement (size ).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical/categorical features, is the target.' },
      { id: 'number_of_trees', role: 'transform', label: 'Number of trees', detail: '.' },
      { id: 'number_of_features_to_cons', role: 'transform', label: 'Number of features to consider per split', detail: '(e.g., for classification, for regression, where is total features).' },
      { id: 'training', role: 'transform', label: 'Training' },
      { id: 'for_each_tree_to', role: 'transform', label: 'For each tree to' },
      { id: 'sample_a_bootstrap_subset_', role: 'input', label: 'Sample a bootstrap subset from with replacement (size )' },
    ],
    beats: [
      { id: 'b1', at: 'training', label: 'Ensemble Learning', detail: 'Combines predictions from multiple decision trees to reduce variance and improve accuracy.' },
      { id: 'b2', at: 'dataset', label: 'Bootstrap Aggregation (Bagging)', detail: 'Trains each tree on a random subset of the data with replacement, ensuring diversity.' },
      { id: 'b3', at: 'number_of_trees', label: 'Random Feature Selection', detail: 'Selects a random subset of features at each split, decorrelating trees and enhancing generalization.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'stacked-generalization-model',
    name: 'Stacked Generalization Model',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Supervised Learning/Ensemble Methods/Stacked Generalization Model.md',
    analogy: 'Information enters at dataset and ends at level-0 (base models).',
    stages: [
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where includes numerical/categorical features, is the target.' },
      { id: 'base_models', role: 'transform', label: 'Base models', detail: '(e.g., Random Forest, XGBoost, neural network).' },
      { id: 'meta_learner', role: 'transform', label: 'Meta-learner', detail: '(e.g., logistic regression, gradient boosting).' },
      { id: 'number_of_folds', role: 'transform', label: 'Number of folds', detail: '(e.g., 5 for cross-validation).' },
      { id: 'training', role: 'transform', label: 'Training' },
      { id: 'level_0_base_models', role: 'transform', label: 'Level-0 (Base Models)' },
    ],
    beats: [
      { id: 'b1', at: 'base_models', label: 'Ensemble Learning', detail: 'Combines multiple base models to reduce bias and variance, enhancing overall accuracy.' },
      { id: 'b2', at: 'training', label: 'Meta-Learning', detail: 'A meta-learner uses base model predictions as features to learn how to combine them optimally.' },
      { id: 'b3', at: 'meta_learner', label: 'Diversity', detail: 'Base models with varied algorithms (e.g., Random Forest, XGBoost, SVM) ensure complementary predictions.' },
    ],
    repoRunner: { templateId: 'none', note: 'Browse-only catalog spec \u2014 this repo has no runner for it, so pressing Run would train nothing. The mechanism above is the published algorithm.' },
    kernelId: null,
    curation: 'extracted',
  },
  {
    catalogKey: 'isolation-forest-anomaly-detection',
    name: 'Isolation Forest (Anomaly Detection)',
    archetype: 'tree-route',
    provenance: 'schematic',
    specPath: 'Machine Learning/Unsupervised Learning/Anomaly Detection/Isolation Forest (Anomaly Detection).md',
    analogy: 'Information enters at anomaly score and ends at training.',
    stages: [
      { id: 'anomaly_score', role: 'score', label: 'Anomaly score', detail: 'Based on the average path length of a data point across isolation trees, where shorter paths indicate anomalie' },
      { id: 'path_length', role: 'transform', label: 'Path length', detail: 'Number of splits required to isolate a point in a tree.' },
      { id: 'anomaly_score_2', role: 'score', label: 'Anomaly score', detail: ', where is the average path length, is a normalization constant for samples.' },
      { id: 'dataset', role: 'input', label: 'Dataset', detail: ', where is a feature vector (no labels required).' },
      { id: 'hyperparameters', role: 'transform', label: 'Hyperparameters', detail: 'Number of trees ( ), subsample size ( ), contamination ratio.' },
      { id: 'training', role: 'transform', label: 'Training' },
    ],
    beats: [
      { id: 'b1', at: 'training', label: 'Random Partitioning', detail: 'Recursively splits data using random feature and threshold selections, forming isolation trees.' },
      { id: 'b2', at: 'dataset', label: 'Anomaly Isolation', detail: 'Anomalies require fewer splits to isolate due to their distinctiveness, resulting in shorter path lengths.' },
      { id: 'b3', at: 'path_length', label: 'Ensemble Learning', detail: 'Combines multiple isolation trees to produce a robust anomaly score.' },
    ],
    repoRunner: { templateId: 'sklearn', note: 'Trained here through the generic sklearn template rather than this architecture\u2019s own implementation.' },
    kernelId: null,
    curation: 'extracted',
  },
];
