/**
 * The lake series catalog, reloaded whenever the generator rewrites it.
 *
 * Generated by `scripts/build_series_catalog.py`. Two things read it: the chart
 * endpoint, where it is the allowlist and the drawing contract, and the Data
 * page profiler, which uses it to say which columns read bars that had not
 * happened yet.
 */

import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { Logger } from "@nestjs/common";
import type { SeriesCatalog, SeriesColumn, SeriesObject } from "@shared/series/types";

const logger = new Logger("SeriesCatalog");
const CATALOG_PATH = path.join(process.cwd(), "packages", "config", "series_catalog.json");

export interface CatalogIndex {
  catalog: SeriesCatalog;
  objects: Map<string, SeriesObject>;
  columns: Map<string, { object: SeriesObject; column: SeriesColumn }>;
}

let catalogPromise: Promise<CatalogIndex> | null = null;
let loadedModifiedMs = 0;
const reloadListeners = new Set<() => void>();

/** Called when the catalog file changes on disk, so dependent caches can clear. */
export function onSeriesCatalogReload(listener: () => void) {
  reloadListeners.add(listener);
}

/**
 * Rebuilding the catalog used to need a server restart to take effect — the
 * first request cached it for the life of the process, so a regenerated file
 * sat unread and the chart kept offering columns the new catalog had dropped.
 * The file's modified time is checked on every call instead.
 */
export async function loadSeriesCatalog(): Promise<CatalogIndex> {
  let modifiedMs = loadedModifiedMs;
  try {
    modifiedMs = (await stat(CATALOG_PATH)).mtimeMs;
  } catch {
    // Missing file: fall through so the read below reports it.
  }
  if (catalogPromise && modifiedMs !== loadedModifiedMs) {
    catalogPromise = null;
    for (const listener of reloadListeners) listener();
  }
  if (!catalogPromise) {
    loadedModifiedMs = modifiedMs;
    catalogPromise = readFile(CATALOG_PATH, "utf8")
      .then((text) => {
        const catalog = JSON.parse(text) as SeriesCatalog;
        const objects = new Map<string, SeriesObject>();
        const columns = new Map<string, { object: SeriesObject; column: SeriesColumn }>();
        for (const object of catalog.objects) {
          objects.set(object.object, object);
          for (const column of object.columns) columns.set(column.id, { object, column });
        }
        logger.log(
          `series catalog: ${catalog.objectCount} objects, ${catalog.columnCount} columns, ` +
            `${catalog.chartableColumnCount} chartable (generated ${catalog.generatedAtIso})`,
        );
        return { catalog, objects, columns };
      })
      .catch((error) => {
        catalogPromise = null;
        throw error;
      });
  }
  return catalogPromise;
}

export const CATALOG_MISSING_MESSAGE =
  "The series catalog has not been built. Run: uv run python scripts/build_series_catalog.py";
