import type { IndicatorDefinition } from "@/market/lib/indicator_registry";

export const MOMENTUM_INDICATORS: IndicatorDefinition[] = [
  {
    id: 'rsi',
    name: 'RSI',
    fullName: 'Relative Strength Index',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'RSI', style: 'line' }],
    referenceLines: [
      { value: 70, color: 'rgba(239, 68, 68, 0.3)' },
      { value: 30, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'macd',
    name: 'MACD',
    fullName: 'Moving Average Convergence Divergence',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 12, min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 26, min: 2, max: 200, step: 1 },
      { key: 'signalPeriod', label: 'Signal', type: 'number', default: 9, min: 2, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'macd', label: 'MACD', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
      { key: 'histogram', label: 'Hist', style: 'histogram' },
    ],
    referenceLines: [
      { value: 0, color: 'rgba(255, 255, 255, 0.1)' },
    ],
  },
  {
    id: 'macdext',
    name: 'MACDEXT',
    fullName: 'MACD with Controllable MA Type',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 12, min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 26, min: 2, max: 200, step: 1 },
      { key: 'signalPeriod', label: 'Signal', type: 'number', default: 9, min: 2, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'macd', label: 'MACD', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
      { key: 'histogram', label: 'Hist', style: 'histogram' },
    ],
  },
  {
    id: 'macdfix',
    name: 'MACDFIX',
    fullName: 'MACD Fixed 12/26',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'signalPeriod', label: 'Signal', type: 'number', default: 9, min: 2, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'macd', label: 'MACD', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
      { key: 'histogram', label: 'Hist', style: 'histogram' },
    ],
  },
  {
    id: 'stochastic',
    name: 'Stochastic',
    fullName: 'Stochastic Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'kPeriod', label: 'K Period', type: 'number', default: 5, min: 1, max: 100, step: 1 },
      { key: 'kSmooth', label: 'K Smooth', type: 'number', default: 3, min: 1, max: 50, step: 1 },
      { key: 'dSmooth', label: 'D Smooth', type: 'number', default: 3, min: 1, max: 50, step: 1 },
    ],
    outputs: [
      { key: 'k', label: 'K', style: 'line' },
      { key: 'd', label: 'D', style: 'line' },
    ],
    referenceLines: [
      { value: 80, color: 'rgba(239, 68, 68, 0.3)' },
      { value: 20, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'stochf',
    name: 'Stoch Fast',
    fullName: 'Stochastic Fast',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'kPeriod', label: 'K Period', type: 'number', default: 5, min: 1, max: 100, step: 1 },
      { key: 'dPeriod', label: 'D Period', type: 'number', default: 3, min: 1, max: 50, step: 1 },
    ],
    outputs: [
      { key: 'k', label: 'K', style: 'line' },
      { key: 'd', label: 'D', style: 'line' },
    ],
  },
  {
    id: 'stochrsi',
    name: 'Stoch RSI',
    fullName: 'Stochastic RSI',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'rsiPeriod', label: 'RSI Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
      { key: 'stochPeriod', label: 'Stoch Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
      { key: 'kSmooth', label: 'K Smooth', type: 'number', default: 3, min: 1, max: 50, step: 1 },
      { key: 'dSmooth', label: 'D Smooth', type: 'number', default: 3, min: 1, max: 50, step: 1 },
    ],
    outputs: [
      { key: 'k', label: 'K', style: 'line' },
      { key: 'd', label: 'D', style: 'line' },
    ],
  },
  {
    id: 'cci',
    name: 'CCI',
    fullName: 'Commodity Channel Index',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CCI', style: 'line' }],
    referenceLines: [
      { value: 100, color: 'rgba(239, 68, 68, 0.3)' },
      { value: -100, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'willr',
    name: 'Williams %R',
    fullName: 'Williams %R',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'WILLR', style: 'line' }],
    referenceLines: [
      { value: -20, color: 'rgba(239, 68, 68, 0.3)' },
      { value: -80, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'momentum',
    name: 'Momentum',
    fullName: 'Momentum',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'MOM', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255, 255, 255, 0.1)' },
    ],
  },
  {
    id: 'roc',
    name: 'ROC',
    fullName: 'Rate of Change',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ROC', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255, 255, 255, 0.1)' },
    ],
  },
  {
    id: 'rocp',
    name: 'ROCP',
    fullName: 'Rate of Change Percentage',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ROCP', style: 'line' }],
  },
  {
    id: 'rocr',
    name: 'ROCR',
    fullName: 'Rate of Change Ratio',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ROCR', style: 'line' }],
  },
  {
    id: 'rocr100',
    name: 'ROCR100',
    fullName: 'Rate of Change Ratio 100 Scale',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ROCR100', style: 'line' }],
  },
  {
    id: 'cmo',
    name: 'CMO',
    fullName: 'Chande Momentum Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CMO', style: 'line' }],
    referenceLines: [
      { value: 50, color: 'rgba(239, 68, 68, 0.3)' },
      { value: -50, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'apo',
    name: 'APO',
    fullName: 'Absolute Price Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 12, min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 26, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'APO', style: 'line' }],
  },
  {
    id: 'ppo',
    name: 'PPO',
    fullName: 'Percentage Price Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 12, min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 26, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'PPO', style: 'line' }],
  },
  {
    id: 'trix',
    name: 'TRIX',
    fullName: '1-day Rate-of-Change of a Triple Smooth EMA',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 30, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'TRIX', style: 'line' }],
  },
  {
    id: 'ultosc',
    name: 'Ultimate Osc',
    fullName: 'Ultimate Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period1', label: 'P1', type: 'number', default: 7, min: 1, max: 50, step: 1 },
      { key: 'period2', label: 'P2', type: 'number', default: 14, min: 1, max: 100, step: 1 },
      { key: 'period3', label: 'P3', type: 'number', default: 28, min: 1, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ULTOSC', style: 'line' }],
  },
  {
    id: 'bop',
    name: 'BOP',
    fullName: 'Balance of Power',
    category: 'momentum',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'BOP', style: 'line' }],
  },
  {
    id: 'ao',
    name: 'AO',
    fullName: 'Awesome Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 5, min: 2, max: 100, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 34, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'AO', style: 'histogram' }],
  },
  {
    id: 'bias',
    name: 'Bias',
    fullName: 'Bias Indicator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 26, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'Bias', style: 'line' }],
  },
  {
    id: 'cfo',
    name: 'CFO',
    fullName: 'Chande Forecast Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 9, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CFO', style: 'line' }],
  },
  {
    id: 'cg',
    name: 'CG',
    fullName: 'Center of Gravity',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CG', style: 'line' }],
  },
  {
    id: 'coppock',
    name: 'Coppock',
    fullName: 'Coppock Curve',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'wmaP', label: 'WMA Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
      { key: 'roc1', label: 'ROC 1', type: 'number', default: 14, min: 1, max: 500, step: 1 },
      { key: 'roc2', label: 'ROC 2', type: 'number', default: 11, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'Coppock', style: 'line' }],
  },
  {
    id: 'crsi',
    name: 'Connors RSI',
    fullName: 'Connors RSI',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'rsiP', label: 'RSI', type: 'number', default: 3, min: 1, max: 100, step: 1 },
      { key: 'streakP', label: 'Streak', type: 'number', default: 2, min: 1, max: 100, step: 1 },
      { key: 'rankP', label: 'Rank', type: 'number', default: 100, min: 10, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CRSI', style: 'line' }],
  },
  {
    id: 'er',
    name: 'ER',
    fullName: 'Efficiency Ratio',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ER', style: 'line' }],
  },
  {
    id: 'fisher',
    name: 'Fisher',
    fullName: 'Fisher Transform',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 9, min: 1, max: 200, step: 1 },
    ],
    outputs: [
      { key: 'fisher', label: 'Fisher', style: 'line' },
      { key: 'trigger', label: 'Trigger', style: 'line' },
    ],
  },
  {
    id: 'inertia',
    name: 'Inertia',
    fullName: 'Inertia Indicator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
      { key: 'rviPeriod', label: 'RVI Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'Inertia', style: 'line' }],
  },
  {
    id: 'kst',
    name: 'KST',
    fullName: 'Know Sure Thing',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'signalP', label: 'Signal', type: 'number', default: 9, min: 1, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'kst', label: 'KST', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
    ],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'pgo',
    name: 'PGO',
    fullName: 'Pretty Good Oscillator',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'PGO', style: 'line' }],
  },
  {
    id: 'psl',
    name: 'PSL',
    fullName: 'Psychological Line',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 12, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'PSL', style: 'line' }],
    referenceLines: [
      { value: 50, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'qqe',
    name: 'QQE',
    fullName: 'Qualitative Quantitative Estimation',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'rsiPeriod', label: 'RSI Period', type: 'number', default: 14, min: 1, max: 100, step: 1 },
      { key: 'smoothFactor', label: 'Smooth', type: 'number', default: 5, min: 1, max: 50, step: 1 },
      { key: 'qqeFactor', label: 'QQE Mult', type: 'number', default: 4.236, min: 1, max: 10, step: 0.1 },
    ],
    outputs: [
      { key: 'qqe', label: 'QQE', style: 'line' },
      { key: 'rsiSmooth', label: 'RSI Smooth', style: 'line' },
      { key: 'upper', label: 'Upper', style: 'line' },
      { key: 'lower', label: 'Lower', style: 'line' },
    ],
  },
  {
    id: 'rsx',
    name: 'RSX',
    fullName: 'Relative Strength Xtra',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'RSX', style: 'line' }],
    referenceLines: [
      { value: 70, color: 'rgba(239,68,68,0.3)' },
      { value: 30, color: 'rgba(34,197,94,0.3)' },
    ],
  },
  {
    id: 'rvgi',
    name: 'RVGI',
    fullName: 'Relative Vigor Index',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 200, step: 1 },
      { key: 'signalP', label: 'Signal', type: 'number', default: 4, min: 1, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'rvgi', label: 'RVGI', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
    ],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'stc',
    name: 'STC',
    fullName: 'Schaff Trend Cycle',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 200, step: 1 },
      { key: 'fastP', label: 'Fast', type: 'number', default: 23, min: 2, max: 100, step: 1 },
      { key: 'slowP', label: 'Slow', type: 'number', default: 50, min: 2, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'STC', style: 'line' }],
    referenceLines: [
      { value: 75, color: 'rgba(239,68,68,0.3)' },
      { value: 25, color: 'rgba(34,197,94,0.3)' },
    ],
  },
  {
    id: 'tsi',
    name: 'TSI',
    fullName: 'True Strength Index',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'longP', label: 'Long', type: 'number', default: 25, min: 2, max: 200, step: 1 },
      { key: 'shortP', label: 'Short', type: 'number', default: 13, min: 2, max: 100, step: 1 },
      { key: 'signalP', label: 'Signal', type: 'number', default: 13, min: 1, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'tsi', label: 'TSI', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
    ],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'smi',
    name: 'SMI',
    fullName: 'Stochastic Momentum Index',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 200, step: 1 },
      { key: 'smoothP', label: 'Smooth', type: 'number', default: 3, min: 1, max: 50, step: 1 },
      { key: 'signalP', label: 'Signal', type: 'number', default: 3, min: 1, max: 50, step: 1 },
    ],
    outputs: [
      { key: 'smi', label: 'SMI', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
    ],
    referenceLines: [
      { value: 40, color: 'rgba(239,68,68,0.3)' },
      { value: -40, color: 'rgba(34,197,94,0.3)' },
    ],
  },
  {
    id: 'squeeze',
    name: 'SQZ',
    fullName: 'Squeeze Momentum',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'bbP', label: 'BB Period', type: 'number', default: 20, min: 2, max: 200, step: 1 },
      { key: 'bbMult', label: 'BB Mult', type: 'number', default: 2, min: 0.5, max: 5, step: 0.1 },
      { key: 'kcP', label: 'KC Period', type: 'number', default: 20, min: 2, max: 200, step: 1 },
      { key: 'kcMult', label: 'KC Mult', type: 'number', default: 1.5, min: 0.5, max: 5, step: 0.1 },
    ],
    outputs: [
      { key: 'momentum', label: 'Momentum', style: 'histogram' },
      { key: 'squeeze', label: 'Squeeze', style: 'line' },
    ],
  },
  {
    id: 'squeeze_pro',
    name: 'SQZ Pro',
    fullName: 'Squeeze Pro',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'bbP', label: 'BB Period', type: 'number', default: 20, min: 2, max: 200, step: 1 },
      { key: 'bbMult', label: 'BB Mult', type: 'number', default: 2, min: 0.5, max: 5, step: 0.1 },
    ],
    outputs: [
      { key: 'momentum', label: 'Momentum', style: 'histogram' },
      { key: 'squeeze', label: 'Squeeze', style: 'line' },
    ],
  },
  {
    id: 'kdj',
    name: 'KDJ',
    fullName: 'KDJ',
    category: 'momentum',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 9, min: 1, max: 200, step: 1 },
      { key: 'signalP', label: 'Signal', type: 'number', default: 3, min: 1, max: 50, step: 1 },
    ],
    outputs: [
      { key: 'k', label: 'K', style: 'line' },
      { key: 'd', label: 'D', style: 'line' },
      { key: 'j', label: 'J', style: 'line' },
    ],
    referenceLines: [
      { value: 80, color: 'rgba(239,68,68,0.3)' },
      { value: 20, color: 'rgba(34,197,94,0.3)' },
    ],
  },
  {
    id: 'wad',
    name: 'WAD',
    fullName: 'Williams Accum/Dist',
    category: 'momentum',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'WAD', style: 'line' }],
  },
];
