import type { IndicatorDefinition } from '../../indicator_registry';

export const VOLUME_INDICATORS: IndicatorDefinition[] = [
  {
    id: 'obv',
    name: 'OBV',
    fullName: 'On Balance Volume',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'OBV', style: 'line' }],
  },
  {
    id: 'ad',
    name: 'AD',
    fullName: 'Accumulation/Distribution',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'A/D', style: 'line' }],
  },
  {
    id: 'adosc',
    name: 'AD Osc',
    fullName: 'Chaikin A/D Oscillator',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'fastPeriod', label: 'Fast', type: 'number', default: 3, min: 2, max: 50, step: 1 },
      { key: 'slowPeriod', label: 'Slow', type: 'number', default: 10, min: 2, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ADOSC', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255, 255, 255, 0.1)' },
    ],
  },
  {
    id: 'mfi',
    name: 'MFI',
    fullName: 'Money Flow Index',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'MFI', style: 'line' }],
    referenceLines: [
      { value: 80, color: 'rgba(239, 68, 68, 0.3)' },
      { value: 20, color: 'rgba(34, 197, 94, 0.3)' },
    ],
  },
  {
    id: 'cmf',
    name: 'CMF',
    fullName: 'Chaikin Money Flow',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'CMF', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'efi',
    name: 'EFI',
    fullName: 'Elder Force Index',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 13, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'EFI', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'eom',
    name: 'EOM',
    fullName: 'Ease of Movement',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
      { key: 'divisor', label: 'Divisor', type: 'number', default: 100000000, min: 1, max: 1000000000, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'EOM', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'kvo',
    name: 'KVO',
    fullName: 'Klinger Volume Oscillator',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'fastP', label: 'Fast', type: 'number', default: 34, min: 2, max: 200, step: 1 },
      { key: 'slowP', label: 'Slow', type: 'number', default: 55, min: 2, max: 200, step: 1 },
      { key: 'signalP', label: 'Signal', type: 'number', default: 13, min: 1, max: 100, step: 1 },
    ],
    outputs: [
      { key: 'kvo', label: 'KVO', style: 'line' },
      { key: 'signal', label: 'Signal', style: 'line' },
    ],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'nvi',
    name: 'NVI',
    fullName: 'Negative Volume Index',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'NVI', style: 'line' }],
  },
  {
    id: 'pvi',
    name: 'PVI',
    fullName: 'Positive Volume Index',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'PVI', style: 'line' }],
  },
  {
    id: 'pvr',
    name: 'PVR',
    fullName: 'Price Volume Rank',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'PVR', style: 'line' }],
  },
  {
    id: 'pvt',
    name: 'PVT',
    fullName: 'Price Volume Trend',
    category: 'volume',
    renderType: 'subchart',
    params: [],
    outputs: [{ key: 'value', label: 'PVT', style: 'line' }],
  },
  {
    id: 'vpci',
    name: 'VPCI',
    fullName: 'Volume Price Confirmation',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'shortP', label: 'Short', type: 'number', default: 5, min: 1, max: 200, step: 1 },
      { key: 'longP', label: 'Long', type: 'number', default: 25, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'VPCI', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
  {
    id: 'vpoc',
    name: 'VPOC',
    fullName: 'Volume Point of Control',
    category: 'volume',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 5, max: 200, step: 1 },
      { key: 'bins', label: 'Price Bins', type: 'number', default: 50, min: 10, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'VPOC', style: 'line' }],
  },
  {
    id: 'vpoc_dist',
    name: 'VPOC Dist',
    fullName: 'VPOC Distance',
    category: 'volume',
    renderType: 'subchart',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 5, max: 200, step: 1 },
      { key: 'bins', label: 'Price Bins', type: 'number', default: 50, min: 10, max: 200, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'VPOC Dist', style: 'line' }],
    referenceLines: [
      { value: 0, color: 'rgba(255,255,255,0.1)' },
    ],
  },
];
