import type { IndicatorDefinition } from '../../indicator_registry';

export const OVERLAP_INDICATORS: IndicatorDefinition[] = [
  {
    id: 'sma',
    name: 'SMA',
    fullName: 'Simple Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'SMA', style: 'line' }],
  },
  {
    id: 'ema',
    name: 'EMA',
    fullName: 'Exponential Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'EMA', style: 'line' }],
  },
  {
    id: 'wma',
    name: 'WMA',
    fullName: 'Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'WMA', style: 'line' }],
  },
  {
    id: 'dema',
    name: 'DEMA',
    fullName: 'Double Exponential Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'DEMA', style: 'line' }],
  },
  {
    id: 'tema',
    name: 'TEMA',
    fullName: 'Triple Exponential Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'TEMA', style: 'line' }],
  },
  {
    id: 'trima',
    name: 'TRIMA',
    fullName: 'Triangular Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 30, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'TRIMA', style: 'line' }],
  },
  {
    id: 't3',
    name: 'T3',
    fullName: 'Triple Exponential T3',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 5, min: 1, max: 200, step: 1 },
      { key: 'vFactor', label: 'V-Factor', type: 'number', default: 0.7, min: 0.0, max: 1.0, step: 0.05 },
    ],
    outputs: [{ key: 'value', label: 'T3', style: 'line' }],
  },
  {
    id: 'bbands',
    name: 'Bollinger Bands',
    fullName: 'Bollinger Bands',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 2, max: 500, step: 1 },
      { key: 'stdDev', label: 'Std Dev', type: 'number', default: 2.0, min: 0.5, max: 5.0, step: 0.5 },
    ],
    outputs: [
      { key: 'upper', label: 'Upper', style: 'line' },
      { key: 'middle', label: 'Middle', style: 'line' },
      { key: 'lower', label: 'Lower', style: 'line' },
    ],
  },
  {
    id: 'kama',
    name: 'KAMA',
    fullName: 'Kaufman Adaptive Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'KAMA', style: 'line' }],
  },
  {
    id: 'mama',
    name: 'MAMA/FAMA',
    fullName: 'MESA Adaptive Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'fastLimit', label: 'Fast Limit', type: 'number', default: 0.5, min: 0.01, max: 0.99, step: 0.01 },
      { key: 'slowLimit', label: 'Slow Limit', type: 'number', default: 0.05, min: 0.01, max: 0.99, step: 0.01 },
    ],
    outputs: [
      { key: 'mama', label: 'MAMA', style: 'line' },
      { key: 'fama', label: 'FAMA', style: 'line' },
    ],
  },
  {
    id: 'midpoint',
    name: 'Midpoint',
    fullName: 'Midpoint Over Period',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'MIDPOINT', style: 'line' }],
  },
  {
    id: 'midprice',
    name: 'Midprice',
    fullName: 'Midpoint Price Over Period',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'MIDPRICE', style: 'line' }],
  },
  {
    id: 'ht_trendline',
    name: 'HT Trendline',
    fullName: 'Hilbert Transform Instantaneous Trendline',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'HT_TRENDLINE', style: 'line' }],
  },
  {
    id: 'tsf',
    name: 'TSF',
    fullName: 'Time Series Forecast',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'TSF', style: 'line' }],
  },
  {
    id: 'linearreg',
    name: 'Linear Reg',
    fullName: 'Linear Regression',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'LINREG', style: 'line' }],
  },
  {
    id: 'psar',
    name: 'Parabolic SAR',
    fullName: 'Parabolic Stop and Reverse',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'step', label: 'Step', type: 'number', default: 0.02, min: 0.001, max: 0.1, step: 0.001 },
      { key: 'max', label: 'Max', type: 'number', default: 0.2, min: 0.01, max: 0.5, step: 0.01 },
    ],
    outputs: [{ key: 'value', label: 'SAR', style: 'line' }],
  },
  {
    id: 'vwap',
    name: 'VWAP',
    fullName: 'Volume Weighted Average Price',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'VWAP', style: 'line' }],
  },
  {
    id: 'hma',
    name: 'HMA',
    fullName: 'Hull Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'HMA', style: 'line' }],
  },
  {
    id: 'alma',
    name: 'ALMA',
    fullName: 'Arnaud Legoux Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 9, min: 1, max: 500, step: 1 },
      { key: 'offset', label: 'Offset', type: 'number', default: 0.85, min: 0, max: 1, step: 0.05 },
      { key: 'sigma', label: 'Sigma', type: 'number', default: 6, min: 1, max: 20, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ALMA', style: 'line' }],
  },
  {
    id: 'fwma',
    name: 'FWMA',
    fullName: 'Fibonacci Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'FWMA', style: 'line' }],
  },
  {
    id: 'pwma',
    name: 'PWMA',
    fullName: 'Pascal Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'PWMA', style: 'line' }],
  },
  {
    id: 'sinwma',
    name: 'SINWMA',
    fullName: 'Sine Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'SINWMA', style: 'line' }],
  },
  {
    id: 'swma',
    name: 'SWMA',
    fullName: 'Symmetrically Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'SWMA', style: 'line' }],
  },
  {
    id: 'vidya',
    name: 'VIDYA',
    fullName: 'Variable Index Dynamic Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'VIDYA', style: 'line' }],
  },
  {
    id: 'vwma',
    name: 'VWMA',
    fullName: 'Volume Weighted Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'VWMA', style: 'line' }],
  },
  {
    id: 'hwma',
    name: 'HWMA',
    fullName: 'Holt-Winter Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'na', label: 'Level', type: 'number', default: 0.2, min: 0, max: 1, step: 0.05 },
      { key: 'nb', label: 'Trend', type: 'number', default: 0.1, min: 0, max: 1, step: 0.05 },
      { key: 'nc', label: 'Seasonal', type: 'number', default: 0.1, min: 0, max: 1, step: 0.05 },
    ],
    outputs: [{ key: 'value', label: 'HWMA', style: 'line' }],
  },
  {
    id: 'mcgd',
    name: 'MCGD',
    fullName: 'McGinley Dynamic',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'MCGD', style: 'line' }],
  },
  {
    id: 'jma',
    name: 'JMA',
    fullName: 'Jurik Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
      { key: 'phase', label: 'Phase', type: 'number', default: 0, min: -100, max: 100, step: 1 },
      { key: 'power', label: 'Power', type: 'number', default: 2, min: 1, max: 10, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'JMA', style: 'line' }],
  },
  {
    id: 'zlma',
    name: 'ZLMA',
    fullName: 'Zero Lag Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'ZLMA', style: 'line' }],
  },
  {
    id: 'rma',
    name: 'RMA',
    fullName: 'Relative Moving Average',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 14, min: 1, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'RMA', style: 'line' }],
  },
  {
    id: 'keltner',
    name: 'Keltner',
    fullName: 'Keltner Channels',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'emaPeriod', label: 'EMA Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
      { key: 'atrPeriod', label: 'ATR Period', type: 'number', default: 10, min: 1, max: 500, step: 1 },
      { key: 'multiplier', label: 'Multiplier', type: 'number', default: 1.5, min: 0.5, max: 5, step: 0.1 },
    ],
    outputs: [
      { key: 'upper', label: 'Upper', style: 'line' },
      { key: 'middle', label: 'Middle', style: 'line' },
      { key: 'lower', label: 'Lower', style: 'line' },
    ],
  },
  {
    id: 'donchian',
    name: 'Donchian',
    fullName: 'Donchian Channels',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [
      { key: 'upper', label: 'Upper', style: 'line' },
      { key: 'middle', label: 'Middle', style: 'line' },
      { key: 'lower', label: 'Lower', style: 'line' },
    ],
  },
  {
    id: 'supertrend',
    name: 'SuperTrend',
    fullName: 'SuperTrend',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 1, max: 200, step: 1 },
      { key: 'multiplier', label: 'Multiplier', type: 'number', default: 3, min: 0.1, max: 10, step: 0.1 },
    ],
    outputs: [{ key: 'value', label: 'SuperTrend', style: 'line' }],
  },
  {
    id: 'ichimoku',
    name: 'Ichimoku',
    fullName: 'Ichimoku Cloud',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'tenkan', label: 'Tenkan', type: 'number', default: 9, min: 1, max: 100, step: 1 },
      { key: 'kijun', label: 'Kijun', type: 'number', default: 26, min: 1, max: 200, step: 1 },
      { key: 'senkou', label: 'Senkou', type: 'number', default: 52, min: 1, max: 500, step: 1 },
    ],
    outputs: [
      { key: 'tenkan', label: 'Tenkan', style: 'line' },
      { key: 'kijun', label: 'Kijun', style: 'line' },
      { key: 'senkouA', label: 'Senkou A', style: 'line' },
      { key: 'senkouB', label: 'Senkou B', style: 'line' },
      { key: 'chikou', label: 'Chikou', style: 'line' },
    ],
  },
  {
    id: 'hilo',
    name: 'HILO',
    fullName: 'Gann HiLo Activator',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 3, min: 1, max: 100, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'HILO', style: 'line' }],
  },
  {
    id: 'ssf',
    name: 'SSF',
    fullName: 'Ehlers Super Smoother Filter',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 10, min: 2, max: 500, step: 1 },
    ],
    outputs: [{ key: 'value', label: 'SSF', style: 'line' }],
  },
  {
    id: 'accbands',
    name: 'AccBands',
    fullName: 'Acceleration Bands',
    category: 'overlap',
    renderType: 'overlay',
    params: [
      { key: 'period', label: 'Period', type: 'number', default: 20, min: 1, max: 500, step: 1 },
    ],
    outputs: [
      { key: 'upper', label: 'Upper', style: 'line' },
      { key: 'middle', label: 'Middle', style: 'line' },
      { key: 'lower', label: 'Lower', style: 'line' },
    ],
  },
  {
    id: 'avgprice',
    name: 'AvgPrice',
    fullName: 'Average Price',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'AVGPRICE', style: 'line' }],
  },
  {
    id: 'medprice',
    name: 'MedPrice',
    fullName: 'Median Price',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'MEDPRICE', style: 'line' }],
  },
  {
    id: 'typprice',
    name: 'TypPrice',
    fullName: 'Typical Price',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'TYPPRICE', style: 'line' }],
  },
  {
    id: 'wclprice',
    name: 'WclPrice',
    fullName: 'Weighted Close Price',
    category: 'overlap',
    renderType: 'overlay',
    params: [],
    outputs: [{ key: 'value', label: 'WCLPRICE', style: 'line' }],
  },
];
