// ─── Color constants for layer types ────────────────────────────────────────
export const LAYER_COLORS = {
  input: "bg-blue-500/15 border-blue-500/30 text-blue-300",
  conv: "bg-violet-500/15 border-violet-500/30 text-violet-300",
  pool: "bg-orange-500/15 border-orange-500/30 text-orange-300",
  recurrent: "bg-amber-500/15 border-amber-500/30 text-amber-300",
  attention: "bg-cyan-500/15 border-cyan-500/30 text-cyan-300",
  ffn: "bg-indigo-500/15 border-indigo-500/30 text-indigo-300",
  dense: "bg-[hsl(var(--data-pos)/0.15)] border-[hsl(var(--data-pos)/0.3)] text-[hsl(var(--data-pos))]",
  norm: "bg-slate-500/15 border-slate-500/30 text-slate-300",
  tree: "bg-[hsl(var(--data-neg)/0.15)] border-[hsl(var(--data-neg)/0.3)] text-[hsl(var(--data-neg))]",
};

export const comparisonData = [
  {
    arch: "CNN",
    color: "text-violet-400",
    speed: 4,
    dataReq: 2,
    seqAware: 2,
    longRange: 1,
    interpret: 3,
    gpu: 2,
    params: "~200K",
  },
  {
    arch: "LSTM",
    color: "text-amber-400",
    speed: 2,
    dataReq: 3,
    seqAware: 5,
    longRange: 3,
    interpret: 2,
    gpu: 2,
    params: "~300K",
  },
  {
    arch: "Transformer",
    color: "text-cyan-400",
    speed: 3,
    dataReq: 4,
    seqAware: 5,
    longRange: 5,
    interpret: 4,
    gpu: 4,
    params: "~500K",
  },
  {
    arch: "XGBoost",
    color: "text-[hsl(var(--data-neg))]",
    speed: 5,
    dataReq: 1,
    seqAware: 0,
    longRange: 0,
    interpret: 5,
    gpu: 0,
    params: "N/A",
  },
  {
    arch: "CNN+LSTM",
    color: "text-[hsl(var(--data-pos))]",
    speed: 2,
    dataReq: 3,
    seqAware: 4,
    longRange: 3,
    interpret: 3,
    gpu: 3,
    params: "~400K",
  },
];
