import os

mapping = {
    '@/components/ui/': '@/shared/ui/',
    '@/components/layout/': '@/shared/layout/',
    '@/contexts/': '@/shared/contexts/',
    '@/components/Layout': '@/shared/layout/Layout',
    '@/components/ErrorBoundary': '@/shared/layout/ErrorBoundary',
    '@/components/LoadingSkeletons': '@/shared/layout/LoadingSkeletons',
    '@/components/CommandPalette': '@/shared/layout/CommandPalette',
    '@/components/NotImplemented': '@/shared/layout/NotImplemented',
    '@/components/QueryErrorBoundary': '@/shared/layout/QueryErrorBoundary',
    '@/lib/utils': '@/shared/utils/utils',
    '@/lib/format': '@/shared/utils/format',
    '@/lib/types': '@/shared/utils/types',
    '@/lib/api_service': '@/infrastructure/api/api_service',
    '@/lib/query_client': '@/infrastructure/api/query_client',
    '@/lib/fetch_array': '@/infrastructure/api/fetch_array',
    '@/lib/ohlcv_cache': '@/infrastructure/storage/ohlcv_cache',
    '@/lib/ring_buffer': '@/infrastructure/storage/ring_buffer',
    '@/lib/error_logger': '@/infrastructure/lib/error_logger',
    '@/lib/prefetch': '@/infrastructure/lib/prefetch',
    '@/hooks/useBreadcrumbs': '@/shared/hooks/useBreadcrumbs',
    '@/hooks/useWebVitals': '@/shared/hooks/useWebVitals',
    '@/hooks/useGlobalShortcuts': '@/shared/hooks/useGlobalShortcuts',
    '@/hooks/useNativeMenu': '@/shared/hooks/useNativeMenu',
    '@/hooks/use-toast': '@/shared/hooks/use-toast',
    '@/hooks/use-mobile': '@/shared/hooks/use-mobile',
    '@/hooks/useDebounce': '@/shared/hooks/useDebounce',
    '@/hooks/useDeferredFilter': '@/shared/hooks/useDeferredFilter',
    '@/pages/MarketData': '@/market/MarketDataPage',
    '@/pages/News': '@/market/NewsPage',
    '@/pages/Watchlist': '@/market/WatchlistPage',
    '@/pages/Portfolio': '@/portfolio/PortfolioPage',
    '@/pages/Paper': '@/portfolio/PaperPage',
    '@/pages/Risk': '@/portfolio/RiskPage',
    '@/pages/Databases': '@/data/DatabasesPage',
    '@/pages/Registry': '@/ml/RegistryPage',
    '@/pages/ModelCatalog': '@/ml/ModelCatalogPage',
    '@/pages/MLStudio': '@/ml/MLStudioPage',
    '@/pages/Forecast': '@/ml/ForecastPage',
    '@/pages/FourierTransform': '@/ml/FourierTransformPage',
    '@/pages/Training': '@/training/TrainingPage',
    '@/pages/Hpo': '@/training/HpoPage',
    '@/pages/HpoDetail': '@/training/HpoDetailPage',
    '@/pages/Curriculum': '@/training/CurriculumPage',
    '@/pages/Backtest': '@/backtest/BacktestPage',
    '@/pages/Settings': '@/system/SettingsPage',
    '@/pages/SystemMatrix': '@/system/SystemMatrixPage',
    '@/pages/Hardware': '@/system/HardwarePage',
    '@/pages/Gpu': '@/system/GpuPage',
    '@/pages/Terminals': '@/system/TerminalsPage',
    '@/pages/ArchitectureExplorer': '@/system/ArchitectureExplorerPage',
    '@/pages/not-found': '@/shared/layout/not-found',
    '@/shared/contexts/TrainingContext': '@/training/lib/TrainingContext',
    '@/hooks/useActiveIndicators': '@/market/lib/useActiveIndicators',
    '@/hooks/useChartOHLCV': '@/market/lib/useChartOHLCV',
    '@/hooks/useIndicatorData': '@/market/lib/useIndicatorData',
    '@/hooks/useIndicatorWorker': '@/market/lib/useIndicatorWorker',
    '@/hooks/useLocalReplay': '@/market/lib/useLocalReplay',
    '@/hooks/useCurriculum': '@/training/lib/useCurriculum',
    '@/hooks/useExperiments': '@/training/lib/useExperiments',
    '@/hooks/useHpoTrials': '@/training/lib/useHpoTrials',
    '@/hooks/useTraining': '@/training/lib/useTraining',
    '@/hooks/useTrainingConfig': '@/training/lib/useTrainingConfig',
    '@/hooks/useTrainingLiveState': '@/training/lib/useTrainingLiveState',
    '@/hooks/useTrainingMetrics': '@/training/lib/useTrainingMetrics',
    '@/hooks/useTrainingSSE': '@/training/lib/useTrainingSSE',
    '@/hooks/useTrainingSync': '@/training/lib/useTrainingSync',
    '@/hooks/useEvaluationResults': '@/ml/lib/useEvaluationResults',
    '@/hooks/useMLData': '@/ml/lib/useMLData',
    '@/hooks/useModelCatalog': '@/ml/lib/useModelCatalog',
    '@/hooks/useModelCheckpoints': '@/ml/lib/useModelCheckpoints',
    '@/hooks/useModelComparison': '@/ml/lib/useModelComparison',
    '@/hooks/useModelHistory': '@/ml/lib/useModelHistory',
    '@/hooks/useRegimeData': '@/ml/lib/useRegimeData',
    '@/hooks/useRegimeSSE': '@/ml/lib/useRegimeSSE',
    '@/hooks/useVisualizationRegistry': '@/ml/lib/useVisualizationRegistry',
    '@/hooks/useTrainedModels': '@/ml/lib/useTrainedModels',
    '@/hooks/useAgentDispatch': '@/deployment/lib/useAgentDispatch',
    '@/hooks/useDeploymentEvents': '@/deployment/lib/useDeploymentEvents',
    '@/hooks/useTradeMetrics': '@/portfolio/lib/useTradeMetrics',
    '@/hooks/useGpuMetrics': '@/system/lib/useGpuMetrics',
    '@/hooks/useSystemManifest': '@/system/lib/useSystemManifest',
    '@/hooks/useSystemMatrix': '@/system/lib/useSystemMatrix',
    '@/hooks/useTerminalSession': '@/system/lib/useTerminalSession',
    '@/hooks/useTimeTracker': '@/system/lib/useTimeTracker',
    '@/hooks/useSpeedAudit': '@/system/lib/useSpeedAudit',
    '@/hooks/useElectron': '@/infrastructure/lib/useElectron',
    '@/hooks/useEventStream': '@/infrastructure/lib/useEventStream',
    '@/hooks/useSSEConnection': '@/infrastructure/lib/useSSEConnection',
    '@/hooks/usePersistedMetrics': '@/infrastructure/lib/usePersistedMetrics',
    '@/hooks/useMetricDescriptions': '@/infrastructure/lib/useMetricDescriptions',
    '@/hooks/usePipelineState': '@/infrastructure/lib/usePipelineState',
    '@/lib/indicators/': '@/market/lib/indicators/',
    '@/lib/candles/': '@/market/lib/candles/',
    '@/lib/indicator_compute': '@/market/lib/indicator_compute',
    '@/lib/indicator_display': '@/market/lib/indicator_display',
    '@/lib/indicator_panels': '@/market/lib/indicator_panels',
    '@/lib/indicator_registry': '@/market/lib/indicator_registry',
    '@/lib/overlay_calculators': '@/market/lib/overlay_calculators',
    '@/lib/subchart_calculators': '@/market/lib/subchart_calculators',
    '@/lib/timeframes': '@/market/lib/timeframes',
    '@/lib/candle_patterns': '@/market/lib/candle_patterns',
    '@/lib/training/': '@/training/lib/training/',
    '@/lib/curriculum/': '@/training/lib/curriculum/',
    '@/lib/models/': '@/ml/lib/models/',
    '@/lib/catalog_types': '@/ml/lib/catalog_types',
    '@/lib/ml_models': '@/ml/lib/ml_models',
    '@/lib/model_resolver': '@/ml/lib/model_resolver',
    '@/lib/metric_extractors': '@/ml/lib/metric_extractors',
    '@/lib/diagnostics-schema': '@/ml/lib/diagnostics-schema',
    '@/lib/calculators/': '@/backtest/lib/calculators/',
    '@/lib/risk': '@/portfolio/lib/risk',
    '@/lib/upload_utils': '@/data/lib/upload_utils'
}

# components mapping
comp_mapping = {
    '@/components/chart/': '@/market/components/chart/',
    '@/components/charts/': '@/market/components/charts/',
    '@/components/indicator-selector/': '@/market/components/indicator-selector/',
    '@/components/IndicatorChartLayout': '@/market/components/IndicatorChartLayout',
    '@/components/TradingChart': '@/market/components/TradingChart',
    '@/components/SubchartPanel': '@/market/components/SubchartPanel',
    '@/components/ReplayControls': '@/market/components/ReplayControls',
    '@/components/IndicatorSelector': '@/market/components/IndicatorSelector',
    '@/components/training/': '@/training/components/',
    '@/components/hpo/': '@/training/components/',
    '@/components/curriculum/': '@/training/components/',
    '@/components/TrainingSyncBanner': '@/training/components/TrainingSyncBanner',
    '@/components/explainable-ai/': '@/ml/components/explainable-ai/',
    '@/components/forecast-visualizer/': '@/ml/components/forecast-visualizer/',
    '@/components/label-generation/': '@/ml/components/label-generation/',
    '@/components/regime-analytics/': '@/ml/components/regime-analytics/',
    '@/components/renderers/': '@/ml/components/renderers/',
    '@/components/ExplainableAI': '@/ml/components/ExplainableAI',
    '@/components/ForecastVisualizer': '@/ml/components/ForecastVisualizer',
    '@/components/LabelGeneration': '@/ml/components/LabelGeneration',
    '@/components/RegimeAnalytics': '@/ml/components/RegimeAnalytics',
    '@/components/RegimeLegend': '@/ml/components/RegimeLegend',
    '@/components/quant/': '@/backtest/components/',
    '@/components/agents/': '@/deployment/components/',
    '@/components/panels/': '@/portfolio/components/',
    '@/components/desktop/': '@/system/components/',
    '@/components/sidebar/': '@/system/components/',
    '@/components/terminal/': '@/system/components/',
    '@/components/SpeedAuditPanel': '@/system/components/SpeedAuditPanel',
    '@/components/Titlebar': '@/system/components/Titlebar',
    '@/components/WindowControls': '@/system/components/WindowControls',
    '@/components/TerminalTabs': '@/system/components/TerminalTabs',
    '@/components/TrainingLogTab': '@/system/components/TrainingLogTab',
    '@/components/renderers/MetricGrid': '@/ml/components/MetricGrid',
    '@/components/training/ConfigStrip': '@/training/ConfigStrip',
    '@/components/training/GroupTabs': '@/training/GroupTabs',
    '@/components/training/LiveTrainingView': '@/training/LiveTrainingView',
    '@/components/training/ModelBrowser': '@/training/ModelBrowser',
    '@/components/terminal/TrainingLogTab': '@/system/components/TrainingLogTab',
    '../types': '../lib/types',
}

mapping.update(comp_mapping)

root_dir = 'apps/web/src'

for root, dirs, files in os.walk(root_dir):
    for file in files:
        if file.endswith('.ts') or file.endswith('.tsx'):
            path = os.path.join(root, file)
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                
                new_content = content
                for old, new in mapping.items():
                    new_content = new_content.replace(old, new)
                
                if new_content != content:
                    with open(path, 'w', encoding='utf-8') as f:
                        f.write(new_content)
                    print(f'Updated {path}')
            except Exception as e:
                print(f'Error processing {path}: {e}')
