/**
 * Lake series — every column in the lake, as something a chart can draw.
 *
 * The catalog is generated by `scripts/build_series_catalog.py`, which measures
 * each column (null fraction, distinct count, min/max/percentiles) and assigns
 * it a family and a render mode from what the values ARE, not from the name
 * alone. The chart never guesses: it reads this.
 *
 * Two rules are load-bearing:
 *   - A column is drawn on the price scale only when it IS a price. Everything
 *     else gets its own pane, because a z-score on the price axis flattens the
 *     candles into a line.
 *   - A column computed from bars AFTER the one it sits on is forward-looking.
 *     It renders as a marker at its own bar and carries a badge, so it can
 *     never be read as a signal that was available at that moment.
 */

export type SeriesFamily =
  | "trend"
  | "momentum"
  | "volatility"
  | "volume"
  | "price_structure"
  | "mean_reversion"
  | "microstructure"
  | "statistics"
  | "pattern"
  | "regime"
  | "label"
  | "trade_level"
  | "reference";

export const SERIES_FAMILY_LABELS: Record<SeriesFamily, string> = {
  trend: "Trend",
  momentum: "Momentum",
  volatility: "Volatility",
  volume: "Volume",
  price_structure: "Price structure",
  mean_reversion: "Mean reversion",
  microstructure: "Microstructure",
  statistics: "Statistics (z-scores)",
  pattern: "Pattern recognition",
  regime: "Regime / state",
  label: "Labels and targets (forward-looking)",
  trade_level: "Trade setup levels",
  reference: "Reference",
};

/** What the numbers look like, measured rather than assumed. */
export type SeriesValueShape =
  | "price_level"          // same order of magnitude as the bar's close
  | "bounded_oscillator"   // 0..100
  | "bounded_ratio"        // 0..1 or -1..1
  | "centered_unbounded"   // zero crossing means something
  | "positive_magnitude"   // >= 0 by construction
  | "cumulative"           // drifts without bound, not comparable across windows
  | "categorical"          // a few discrete states
  | "binary"               // 0/1
  | "timestamp"
  | "text";

/** How the chart draws it. */
export type SeriesRenderMode =
  | "price_overlay"   // on the candles, at its literal value
  | "pane_line"
  | "pane_histogram"
  | "pane_step"       // discrete states, never interpolated between them
  | "markers"         // one mark on the bar it belongs to
  | "background";     // shading behind the candles

export interface SeriesReferenceLine {
  value: number;
  label: string;
  /** "clip" marks an artifact of normalisation, not a level the market respects. */
  kind: "zero" | "level" | "clip";
}

export interface SeriesColumn {
  /** Stable id used as the indicator id: lake:<object>:<column>. */
  id: string;
  object: string;
  column: string;
  /** Full words, for anything a person reads. */
  label: string;
  family: SeriesFamily;
  valueShape: SeriesValueShape;
  renderMode: SeriesRenderMode;
  duckdbType: string;
  nullFraction: number;
  distinctApproximate: number;
  minimum: number | null;
  maximum: number | null;
  percentile01: number | null;
  percentile50: number | null;
  percentile99: number | null;
  referenceLines: SeriesReferenceLine[];
  /**
   * Computed from bars after this one. Renders as a marker with a badge and is
   * grouped apart from live indicators.
   */
  forwardLooking: boolean;
  /** Reason this column is not offered as a chart indicator, if it is not. */
  unavailableReason?: string;
}

export interface SeriesObject {
  object: string;
  /** Where the bars come from, in plain words. */
  description: string;
  timestampColumn: string;
  symbolColumn: string | null;
  /** "1m", "5m", "1s", or null when the object is not a per-bar series. */
  timeframe: string | null;
  rowCount: number;
  firstTimestampSeconds: number | null;
  lastTimestampSeconds: number | null;
  /** Symbols this object actually carries, when it is scoped to a few. */
  symbols: string[];
  /** One row per bar, or one row per event. Event tables only ever render as markers. */
  grain: "per_bar" | "per_event" | "dimension";
  columns: SeriesColumn[];
}

export interface SeriesCatalog {
  generatedAtIso: string;
  /** The snapshot the measurements were taken against. */
  source: string;
  objectCount: number;
  columnCount: number;
  chartableColumnCount: number;
  objects: SeriesObject[];
}

// ─── Fetching a series for a viewport ────────────────────────────────────────

export interface SeriesRequest {
  /** lake:<object>:<column> ids, at most SERIES_MAX_COLUMNS per request. */
  ids: string[];
  symbol: string;
  timeframe: string;
  startTimestampSeconds: number;
  endTimestampSeconds: number;
  /** Points per series after bucketing; the chart asks for about its pixel width. */
  maxPoints: number;
}

export interface SeriesPoint {
  timestampSeconds: number;
  value: number | null;
}

export interface SeriesResponse {
  symbol: string;
  timeframe: string;
  series: Array<{
    id: string;
    object: string;
    column: string;
    family: SeriesFamily;
    renderMode: SeriesRenderMode;
    referenceLines: SeriesReferenceLine[];
    forwardLooking: boolean;
    /** Bucketed when the window holds more bars than maxPoints. */
    downsampled: boolean;
    pointCount: number;
    points: SeriesPoint[];
    /** Set when this column has no rows in the requested window. */
    emptyReason?: string;
  }>;
}

export const SERIES_MAX_COLUMNS = 8;
/**
 * Markers are drawn one per firing bar with a label beside each. Several
 * thousand of them froze the renderer outright, so a marker column is thinned
 * to this many across the window and says so when it is.
 */
export const SERIES_MAX_MARKERS = 250;
export const SERIES_MAX_POINTS = 5000;
