#!/usr/bin/env node
/**
 * Writes src/server/studies/handlers/index.ts: one import per handler file in
 * that directory, so adding a study never edits a shared file by hand.
 * Run after adding or removing a handler:  node scripts/build_study_index.mjs
 * `--check` exits 1 when the index is out of date (used by the registry test).
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const directory = path.join(root, "src", "server", "studies", "handlers");
const indexPath = path.join(directory, "index.ts");

const files = readdirSync(directory)
  .filter((name) => name.endsWith(".ts") && name !== "index.ts" && !name.endsWith(".test.ts"))
  .sort();

const identifier = (file) =>
  file
    .replace(/\.ts$/, "")
    .replace(/[^A-Za-z0-9]+(.)/g, (_, letter) => letter.toUpperCase())
    .replace(/^[0-9]/, (digit) => `_${digit}`);

const lines = [
  "// Generated by scripts/build_study_index.mjs: one import per handler file. Do not edit by hand.",
  'import type { StudyHandler } from "../types";',
  ...files.map((file) => `import ${identifier(file)} from "./${file.replace(/\.ts$/, "")}";`),
  "",
  "export const STUDY_HANDLERS: StudyHandler[] = [",
  ...files.map((file) => `  ${identifier(file)} as StudyHandler,`),
  "];",
  "",
];
const next = lines.join("\n");

let current = "";
try {
  current = readFileSync(indexPath, "utf8");
} catch {
  current = "";
}

if (process.argv.includes("--check")) {
  if (current.replace(/\r\n/g, "\n") !== next) {
    console.error("src/server/studies/handlers/index.ts is out of date: run node scripts/build_study_index.mjs");
    process.exit(1);
  }
  console.log(`study index up to date (${files.length} handlers)`);
} else {
  writeFileSync(indexPath, next);
  console.log(`wrote ${path.relative(root, indexPath)} with ${files.length} handlers`);
}
