/**
 * The lake series catalog, loaded once.
 *
 * Generated by `scripts/build_series_catalog.py`. Two things read it: the chart
 * endpoint, where it is the allowlist and the drawing contract, and the Data
 * page profiler, which uses it to say which columns read bars that had not
 * happened yet.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import { Logger } from "@nestjs/common";
import type { SeriesCatalog, SeriesColumn, SeriesObject } from "../../shared/series/types";

const logger = new Logger("SeriesCatalog");
const CATALOG_PATH = path.join(process.cwd(), "src", "config", "series_catalog.json");

export interface CatalogIndex {
  catalog: SeriesCatalog;
  objects: Map<string, SeriesObject>;
  columns: Map<string, { object: SeriesObject; column: SeriesColumn }>;
}

let catalogPromise: Promise<CatalogIndex> | null = null;

export function loadSeriesCatalog(): Promise<CatalogIndex> {
  if (!catalogPromise) {
    catalogPromise = readFile(CATALOG_PATH, "utf8")
      .then((text) => {
        const catalog = JSON.parse(text) as SeriesCatalog;
        const objects = new Map<string, SeriesObject>();
        const columns = new Map<string, { object: SeriesObject; column: SeriesColumn }>();
        for (const object of catalog.objects) {
          objects.set(object.object, object);
          for (const column of object.columns) columns.set(column.id, { object, column });
        }
        logger.log(
          `series catalog: ${catalog.objectCount} objects, ${catalog.columnCount} columns, ` +
            `${catalog.chartableColumnCount} chartable (generated ${catalog.generatedAtIso})`,
        );
        return { catalog, objects, columns };
      })
      .catch((error) => {
        catalogPromise = null;
        throw error;
      });
  }
  return catalogPromise;
}

export const CATALOG_MISSING_MESSAGE =
  "The series catalog has not been built. Run: uv run python scripts/build_series_catalog.py";
