 {
  id: "gen-vae",
  title: "Variational Autoencoders",
  description: "Master Variational Autoencoders from first principles: derive the ELBO from maximum likelihood, understand why the reparameterization trick enables gradient-based optimization through stochastic nodes, explore β-VAE for disentangled representations and Conditional VAE for regime-aware generation, and apply these generative models to synthesize realistic forex market scenarios for stress testing and anomaly detection.",
  estimatedMinutes: 75,
  difficulty: "advanced",
  relatedModels: ["vae", "autoencoder"],
  sections: [
    {
      type: "objective",
      content: "By the end of this lesson you will understand why standard autoencoders cannot generate new data, how variational inference transforms generation into an optimization problem, and how to build, train, and deploy VAEs for financial applications including synthetic scenario generation and anomaly detection.",
      keyTakeaways: [
        "Derive the Evidence Lower Bound (ELBO) from the intractable marginal likelihood using Jensen's inequality and understand each term's role",
        "Prove why naive sampling blocks backpropagation and how the reparameterization trick restores differentiability through deterministic transformation of noise",
        "Compute KL divergence analytically for univariate and multivariate Gaussian distributions with concrete numerical results",
        "Implement a complete VAE in PyTorch with encoder, decoder, reparameterization, and composite ELBO loss",
        "Understand β-VAE's disentanglement mechanism and how β controls the reconstruction-regularization trade-off",
        "Build a Conditional VAE that generates regime-specific forex scenarios conditioned on volatility state",
        "Apply latent space interpolation to smoothly transition between market regimes and generate stress-test scenarios",
        "Use VAE reconstruction error as an anomaly score to detect unusual market conditions in live data"
      ]
    },
    {
      type: "theory",
      title: "From Maximum Likelihood to the ELBO",
      content: `We want to learn a generative model p_θ(x) that assigns high probability to observed data (e.g., windows of forex returns). We posit a latent variable model: each observation x is generated by first sampling a latent code z ~ p(z) = N(0, I), then sampling x ~ p_θ(x|z). The marginal likelihood is:\n\np_θ(x) = ∫ p_θ(x|z) p(z) dz\n\nThis integral is intractable because we would need to evaluate p_θ(x|z) for every possible z in a continuous, high-dimensional space. For a neural network decoder, there is no closed-form solution. We cannot compute p_θ(x), so we cannot directly maximize log p_θ(x) over our dataset.\n\nTo make progress, we introduce a variational approximation q_φ(z|x) — an encoder network that maps each x to an approximate posterior over z. We derive a tractable lower bound on log p_θ(x) as follows. Start from the marginal likelihood and multiply/divide by q_φ(z|x) inside the integral:\n\nlog p_θ(x) = log ∫ p_θ(x, z) dz\n            = log ∫ p_θ(x, z) · [q_φ(z|x) / q_φ(z|x)] dz\n            = log ∫ q_φ(z|x) · [p_θ(x, z) / q_φ(z|x)] dz\n            = log E_{q_φ(z|x)} [p_θ(x, z) / q_φ(z|x)]\n\nBy Jensen's inequality (log is concave, so log E[·] ≥ E[log(·)]):\n\nlog p_θ(x) ≥ E_{q_φ(z|x)} [log p_θ(x, z) / q_φ(z|x)]\n            = E_{q_φ(z|x)} [log p_θ(x, z) - log q_φ(z|x)]\n\nThis is the Evidence Lower Bound (ELBO). We expand p_θ(x, z) = p_θ(x|z) p(z):\n\nELBO = E_{q_φ(z|x)} [log p_θ(x|z) + log p(z) - log q_φ(z|x)]\n     = E_{q_φ(z|x)} [log p_θ(x|z)] + E_{q_φ(z|x)} [log p(z) - log q_φ(z|x)]\n     = E_{q_φ(z|x)} [log p_θ(x|z)] - KL(q_φ(z|x) || p(z))\n\nThe first term is the reconstruction likelihood — it measures how well the decoder reconstructs x from samples of z drawn from the encoder. The second term is the KL divergence — it penalizes the encoder for deviating from the prior p(z) = N(0, I), acting as a regularizer that keeps the latent space structured.\n\nThe gap between log p_θ(x) and the ELBO is exactly KL(q_φ(z|x) || p_θ(z|x)), the divergence between our approximate and true posterior. So maximizing the ELBO simultaneously maximizes the data likelihood and tightens the approximation.\n\nConcrete numerical example: Let z be 1-dimensional, q_φ(z|x) = N(μ=0.5, σ²=0.09) (so σ=0.3), and p(z) = N(0, 1). The KL divergence between two univariate Gaussians N(μ₁, σ₁²) and N(μ₂, σ₂²) is:\n\nKL = log(σ₂/σ₁) + (σ₁² + (μ₁ - μ₂)²) / (2σ₂²) - 1/2\n\nPlugging in μ₁=0.5, σ₁=0.3, μ₂=0, σ₂=1:\n\nKL = log(1/0.3) + (0.09 + 0.25) / (2·1) - 0.5\n   = log(3.333) + 0.34/2 - 0.5\n   = 1.204 + 0.17 - 0.5\n   = 0.874 nats\n\nThis means the encoder's posterior is 0.874 nats away from the prior. If the reconstruction term contributes, say, -2.5 nats (negative log-likelihood of decoded output), then ELBO = -2.5 - 0.874 = -3.374. Training maximizes this (equivalently minimizes -ELBO = 3.374), pushing the encoder toward the prior while improving reconstruction.`
    },
    {
      type: "theory",
      title: "The Reparameterization Trick",
      content: `To optimize the ELBO via stochastic gradient descent, we need gradients of the reconstruction term E_{q_φ(z|x)}[log p_θ(x|z)] with respect to φ (the encoder parameters). The challenge: this expectation is taken over q_φ(z|x), which itself depends on φ. If we sample z ~ q_φ(z|x) = N(μ_φ(x), σ_φ(x)²), the sampling operation is non-differentiable — it creates a stochastic node in the computation graph through which gradients cannot flow.\n\nFormally, ∇_φ E_{q_φ}[f(z)] = ∇_φ ∫ f(z) q_φ(z|x) dz. We cannot simply push the gradient inside because q_φ itself depends on φ. The REINFORCE estimator (score function estimator) can handle this: ∇_φ E_{q_φ}[f(z)] = E_{q_φ}[f(z) ∇_φ log q_φ(z|x)], but this estimator has notoriously high variance, requiring thousands of samples per gradient step, making it impractical for training deep networks.\n\nThe reparameterization trick resolves this by expressing the random variable z as a deterministic, differentiable function of φ and an independent noise variable ε:\n\nε ~ N(0, I)    (sample noise — independent of φ)\nz = μ_φ(x) + σ_φ(x) ⊙ ε    (deterministic transform)\n\nNow z is a deterministic function of (μ, σ, ε), and since ε does not depend on φ, we can push the gradient through:\n\n∇_φ E_{ε~N(0,I)}[f(μ_φ + σ_φ ⊙ ε)]\n= E_{ε~N(0,I)}[∇_φ f(μ_φ + σ_φ ⊙ ε)]    (gradient moves inside expectation)\n\nThe key partial derivatives are:\n\n∂z/∂μ = I    (identity — z moves 1-for-1 with μ)\n∂z/∂σ = diag(ε)    (z's sensitivity to σ equals the sampled noise)\n∂z/∂ε = diag(σ)    (used for forward pass, not parameter gradients)\n\nConcrete numerical example: Suppose the encoder outputs μ = 0.5, σ = 0.3 for some input x, and we sample ε = 1.2 from N(0,1). Then:\n\nz = 0.5 + 0.3 × 1.2 = 0.5 + 0.36 = 0.86\n\nSuppose the downstream loss gives ∂L/∂z = -0.4 (the loss wants z to decrease). By chain rule:\n\n∂L/∂μ = ∂L/∂z × ∂z/∂μ = -0.4 × 1.0 = -0.4\n∂L/∂σ = ∂L/∂z × ∂z/∂σ = -0.4 × 1.2 = -0.48\n\nSo gradient descent would decrease both μ and σ. Note that ∂L/∂σ depends on the particular ε sampled — this introduces some variance, but far less than REINFORCE. In practice, we parameterize log σ instead of σ to ensure σ > 0:\n\n∂L/∂(log σ) = ∂L/∂σ × ∂σ/∂(log σ) = ∂L/∂σ × σ = -0.48 × 0.3 = -0.144\n\nThis is exactly what PyTorch computes automatically when we write z = mu + torch.exp(log_var * 0.5) * eps. The entire path from input x → encoder → (μ, log σ²) → z → decoder → reconstruction loss is now fully differentiable, enabling standard backpropagation and Adam optimization.`
    },
    {
      type: "theory",
      title: "β-VAE, Conditional VAE, and Latent Space Properties",
      content: `The standard VAE balances reconstruction and regularization equally. β-VAE (Higgins et al., 2017) introduces a hyperparameter β that explicitly controls this trade-off:\n\nL_β-VAE = E_{q_φ(z|x)}[log p_θ(x|z)] - β · KL(q_φ(z|x) || p(z))\n\nWhen β = 1, we recover the standard VAE. When β > 1, the KL penalty is amplified, forcing the encoder to compress information more aggressively into a structured latent space. This pressure encourages disentanglement — each latent dimension tends to capture a single independent factor of variation. For forex data, β > 1 might separate volatility, trend, and mean-reversion into distinct dimensions. When β < 1 (or β → 0), the KL penalty vanishes and the model degenerates toward a standard autoencoder with no meaningful latent structure — reconstruction is perfect but generation produces nonsense because the latent space has gaps and irregular geometry.\n\nConditional VAE (CVAE) extends the framework by conditioning both the encoder and decoder on an observed label or context variable y:\n\nEncoder: q_φ(z|x, y)    — posterior depends on both data and condition\nDecoder: p_θ(x|z, y)    — generation depends on both latent code and condition\nPrior: p(z|y) or p(z) = N(0, I)    — prior may or may not depend on y\n\nThe CVAE ELBO becomes:\n\nL_CVAE = E_{q_φ(z|x,y)}[log p_θ(x|z, y)] - KL(q_φ(z|x, y) || p(z))\n\nIn a forex context, y could represent the volatility regime (low/medium/high) or a macroeconomic indicator. The CVAE learns to generate realistic return sequences specific to each regime. For example, conditioning on y = "high volatility" produces wider return distributions, while y = "low volatility" produces tighter ones. At generation time, we choose y, sample z ~ p(z), and decode to get a synthetic scenario consistent with that regime.\n\nLatent space interpolation leverages the smooth, continuous geometry enforced by the KL regularizer. Given two data points x₁ and x₂, we encode them to obtain z₁ = μ_φ(x₁) and z₂ = μ_φ(x₂), then interpolate:\n\nz_interp(t) = (1 - t) · z₁ + t · z₂,    t ∈ [0, 1]\n\nDecoding z_interp(t) for t = 0, 0.25, 0.5, 0.75, 1 produces a smooth sequence of outputs transitioning from x₁-like to x₂-like. Unlike standard autoencoders, the VAE's regularized latent space ensures intermediate points decode to plausible outputs rather than noise. For stress testing, we can interpolate between a calm market state and a crisis state (e.g., 2008 GFC), generating a continuum of increasingly stressed scenarios.\n\nNumerical interpolation example: Suppose z₁ = [0.2, -0.8] (calm market) and z₂ = [1.5, 0.9] (crisis). At t = 0.4:\n\nz_interp = (1 - 0.4) · [0.2, -0.8] + 0.4 · [1.5, 0.9]\n         = 0.6 · [0.2, -0.8] + 0.4 · [1.5, 0.9]\n         = [0.12, -0.48] + [0.60, 0.36]\n         = [0.72, -0.12]\n\nDecoding [0.72, -0.12] should produce a moderately stressed scenario — higher volatility than calm but not full crisis. This gives risk managers a parametric lever (t) to control stress severity.`
    },
    {
      type: "theory",
      title: "KL Divergence for Multivariate Gaussians",
      content: `In practice, VAE latent spaces are d-dimensional, so we need the multivariate KL divergence. For q_φ(z|x) = N(μ, Σ) and p(z) = N(0, I), the KL divergence is:\n\nKL(N(μ, Σ) || N(0, I)) = ½ [tr(Σ) + μᵀμ - d - ln det(Σ)]\n\nDerivation: The KL divergence between two multivariate Gaussians N(μ₁, Σ₁) and N(μ₂, Σ₂) is:\n\nKL = ½ [ln(det Σ₂ / det Σ₁) + tr(Σ₂⁻¹ Σ₁) + (μ₂ - μ₁)ᵀ Σ₂⁻¹ (μ₂ - μ₁) - d]\n\nWith μ₂ = 0, Σ₂ = I:\n\nln(det I / det Σ₁) = -ln det Σ₁\ntr(I⁻¹ Σ₁) = tr(Σ₁)\n(0 - μ₁)ᵀ I⁻¹ (0 - μ₁) = μ₁ᵀ μ₁\n\nSo: KL = ½ [-ln det Σ₁ + tr(Σ₁) + μ₁ᵀμ₁ - d]\n       = ½ [tr(Σ) + μᵀμ - d - ln det(Σ)]\n\nIn VAEs we use a diagonal covariance Σ = diag(σ₁², σ₂², ..., σ_d²), so:\n\ntr(Σ) = Σᵢ σᵢ²\nln det(Σ) = Σᵢ ln σᵢ²\nμᵀμ = Σᵢ μᵢ²\n\nKL = ½ Σᵢ [σᵢ² + μᵢ² - 1 - ln σᵢ²]\n\nThis is the formula implemented in PyTorch as: kl_loss = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp()), where log_var = ln σ². Each dimension contributes independently, which is why we sum over dimensions.\n\nConcrete numerical example with d = 2: Let μ = [0.5, -0.3], σ² = [0.09, 0.16] (so σ = [0.3, 0.4]).\n\nDimension 1: σ₁² + μ₁² - 1 - ln σ₁² = 0.09 + 0.25 - 1 - ln(0.09)\n           = 0.09 + 0.25 - 1 - (-2.408) = 0.09 + 0.25 - 1 + 2.408 = 1.748\n\nDimension 2: σ₂² + μ₂² - 1 - ln σ₂² = 0.16 + 0.09 - 1 - ln(0.16)\n           = 0.16 + 0.09 - 1 - (-1.833) = 0.16 + 0.09 - 1 + 1.833 = 1.083\n\nKL = ½ (1.748 + 1.083) = ½ × 2.831 = 1.416 nats\n\nVerification with log_var parameterization: log_var = [ln(0.09), ln(0.16)] = [-2.408, -1.833].\n\n-0.5 × Σᵢ(1 + log_varᵢ - μᵢ² - exp(log_varᵢ))\n= -0.5 × [(1 + (-2.408) - 0.25 - 0.09) + (1 + (-1.833) - 0.09 - 0.16)]\n= -0.5 × [(1 - 2.408 - 0.25 - 0.09) + (1 - 1.833 - 0.09 - 0.16)]\n= -0.5 × [(-1.748) + (-1.083)]\n= -0.5 × (-2.831) = 1.416 nats ✓\n\nThis matches, confirming the equivalence of the two formulations. In practice, for a VAE with d = 32 latent dimensions, the total KL is the sum of 32 such per-dimension terms, typically ranging from 10–50 nats for a well-trained model.`
    },
    {
      type: "intuition",
      title: "The Postal System Analogy",
      analogy: "A VAE is like a postal system where the encoder writes a compressed address (latent code) for each package (data point), and the decoder delivers a reconstruction based on that address. The KL divergence is a zoning law that forces all addresses to follow a standard zip-code format (the prior N(0,I)). Without zoning, the encoder could invent bizarre private codes — perfect for reconstruction but meaningless to anyone else. With zoning, nearby zip codes correspond to nearby neighborhoods, so you can invent a new zip code between two known ones and the mail carrier (decoder) will deliver to a sensible location in between. The β knob controls how strictly zoning is enforced: too strict (β>>1) and everything goes to the same generic neighborhood; too loose (β→0) and there is no structure at all.",
      content: "The encoder compresses each data point into a 'zip code' in latent space. The KL divergence acts as a zoning regulation, forcing these codes to follow a standard format (the Gaussian prior). This is why VAEs can generate new data — you can sample any valid zip code and the decoder knows how to deliver a plausible output. The reparameterization trick is like using a standardized map overlay (ε) that the encoder annotates with local offsets (μ, σ) — the map itself has no dependence on the encoder's parameters, so you can trace back through the annotation process to improve the encoder.",
      emoji: "📮"
    },
    {
      type: "intuition",
      title: "The Blurry Photograph Darkroom",
      analogy: "Imagine a photography darkroom where the encoder is a camera that deliberately takes slightly blurry photos (adding Gaussian noise via the stochastic encoding), and the decoder tries to reconstruct sharp images from these blurry versions. The blurriness (variance σ²) is intentional — it forces the system to learn the essence of each image rather than memorizing pixel-perfect copies. The KL penalty is like a rule that says your blur level must be close to a standard setting. If you use too little blur (σ→0), you get perfect copies but can't generate anything new. If you use too much blur (σ→1, μ→0), everything looks the same. The sweet spot produces photos that are slightly soft but capture the true structure, and you can smoothly adjust the focus (interpolate in latent space) to transition between scenes.",
      content: "The VAE's encoder intentionally introduces controlled noise when mapping data to latent space — this is the 'blur' that prevents memorization and encourages learning generalizable structure. The reconstruction loss pushes for sharpness (fidelity) while the KL loss pushes for standardized blur (regularity). The tension between these two forces creates a latent space where every point decodes to something meaningful. For forex data, the 'blur' means the model learns the statistical essence of market regimes rather than memorizing specific price sequences, enabling generation of novel but realistic scenarios.",
      emoji: "📸"
    },
    {
      type: "code",
      title: "Complete VAE for Forex Returns",
      language: "python",
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# Simulate forex return windows: 1000 samples, each a 20-step return sequence
np.random.seed(42)
torch.manual_seed(42)
n_samples, seq_len = 1000, 20
# Mix of two regimes: low-vol (70%) and high-vol (30%)
regime = np.random.choice([0, 1], size=n_samples, p=[0.7, 0.3])
returns = np.where(regime[:, None] == 0,
    np.random.normal(0.0001, 0.005, (n_samples, seq_len)),
    np.random.normal(-0.0002, 0.015, (n_samples, seq_len))
).astype(np.float32)
data = torch.tensor(returns)

class VAE(nn.Module):
    def __init__(self, input_dim=20, hidden_dim=64, latent_dim=8):
        super().__init__()
        # Encoder
        self.enc_fc1 = nn.Linear(input_dim, hidden_dim)
        self.enc_fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        # Decoder
        self.dec_fc1 = nn.Linear(latent_dim, hidden_dim)
        self.dec_fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.dec_out = nn.Linear(hidden_dim, input_dim)

    def encode(self, x):
        h = F.relu(self.enc_fc1(x))
        h = F.relu(self.enc_fc2(h))
        return self.fc_mu(h), self.fc_logvar(h)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + std * eps

    def decode(self, z):
        h = F.relu(self.dec_fc1(z))
        h = F.relu(self.dec_fc2(h))
        return self.dec_out(h)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

def vae_loss(recon_x, x, mu, logvar):
    recon = F.mse_loss(recon_x, x, reduction="sum")
    kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon + kl, recon, kl

model = VAE()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

print(f"Training VAE: {sum(p.numel() for p in model.parameters())} parameters")
for epoch in range(1, 51):
    model.train()
    idx = torch.randperm(n_samples)
    total_loss, total_recon, total_kl = 0, 0, 0
    for i in range(0, n_samples, 128):
        batch = data[idx[i:i+128]]
        recon, mu, logvar = model(batch)
        loss, recon_l, kl_l = vae_loss(recon, batch, mu, logvar)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        total_recon += recon_l.item()
        total_kl += kl_l.item()
    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d} | Loss: {total_loss/n_samples:.4f} | "
              f"Recon: {total_recon/n_samples:.4f} | KL: {total_kl/n_samples:.4f}")

# Generate synthetic scenarios
model.eval()
with torch.no_grad():
    z_sample = torch.randn(5, 8)
    generated = model.decode(z_sample).numpy()
    for i, g in enumerate(generated):
        vol = np.std(g) * 100
        print(f"Scenario {i+1}: mean={np.mean(g)*1e4:.2f} bps, vol={vol:.3f}%, "
              f"min={np.min(g)*1e4:.1f} bps, max={np.max(g)*1e4:.1f} bps")`,
      explanation: "This complete VAE implementation processes 20-step forex return windows through a 2-layer encoder that outputs μ and log σ² for an 8-dimensional latent space. The reparameterization trick (z = μ + σ⊙ε) enables backpropagation through the sampling step. The loss combines MSE reconstruction with the closed-form KL divergence for diagonal Gaussians. After training for 50 epochs, we generate 5 novel scenarios by sampling z ~ N(0,I) and decoding, showing that the VAE learns to produce realistic return statistics matching the training distribution's two-regime mixture."
    },
    {
      type: "code",
      title: "β-VAE with Latent Space Interpolation",
      language: "python",
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

np.random.seed(42)
torch.manual_seed(42)

# Generate two-regime forex data
n_samples, seq_len = 800, 20
regime = np.random.choice([0, 1], size=n_samples, p=[0.6, 0.4])
returns = np.where(regime[:, None] == 0,
    np.random.normal(0.0002, 0.004, (n_samples, seq_len)),
    np.random.normal(-0.0003, 0.018, (n_samples, seq_len))
).astype(np.float32)
data = torch.tensor(returns)

class BetaVAE(nn.Module):
    def __init__(self, input_dim=20, latent_dim=4):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(input_dim, 48), nn.ReLU(),
                                     nn.Linear(48, 32), nn.ReLU())
        self.fc_mu = nn.Linear(32, latent_dim)
        self.fc_logvar = nn.Linear(32, latent_dim)
        self.decoder = nn.Sequential(nn.Linear(latent_dim, 32), nn.ReLU(),
                                     nn.Linear(32, 48), nn.ReLU(),
                                     nn.Linear(48, input_dim))

    def forward(self, x):
        h = self.encoder(x)
        mu, logvar = self.fc_mu(h), self.fc_logvar(h)
        z = mu + torch.exp(0.5 * logvar) * torch.randn_like(mu)
        return self.decoder(z), mu, logvar

def train_beta_vae(beta, epochs=60):
    model = BetaVAE()
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)
    for epoch in range(1, epochs + 1):
        recon_x, mu, logvar = model(data)
        recon = F.mse_loss(recon_x, data, reduction="sum")
        kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
        loss = recon + beta * kl
        opt.zero_grad(); loss.backward(); opt.step()
        if epoch % 20 == 0:
            print(f"  [beta={beta}] Epoch {epoch} | Recon: {recon.item()/len(data):.4f} "
                  f"| KL: {kl.item()/len(data):.4f}")
    return model

# Compare beta values
for beta in [0.1, 1.0, 4.0]:
    print(f"\\nTraining beta-VAE with beta={beta}")
    model = train_beta_vae(beta)

# Latent interpolation between calm and volatile samples
print("\\n--- Latent Space Interpolation ---")
model_interp = train_beta_vae(beta=2.0, epochs=80)
model_interp.eval()
with torch.no_grad():
    calm_idx = np.argmin(np.std(returns, axis=1))
    crisis_idx = np.argmax(np.std(returns, axis=1))
    z_calm = model_interp.fc_mu(model_interp.encoder(data[calm_idx:calm_idx+1]))
    z_crisis = model_interp.fc_mu(model_interp.encoder(data[crisis_idx:crisis_idx+1]))
    print(f"Calm latent:   {z_calm.squeeze().numpy().round(3)}")
    print(f"Crisis latent: {z_crisis.squeeze().numpy().round(3)}")
    for t in [0.0, 0.25, 0.5, 0.75, 1.0]:
        z_t = (1 - t) * z_calm + t * z_crisis
        gen = model_interp.decoder(z_t).squeeze().numpy()
        print(f"  t={t:.2f} | vol={np.std(gen)*100:.4f}% | "
              f"mean={np.mean(gen)*1e4:.2f} bps | range=[{np.min(gen)*1e4:.1f}, "
              f"{np.max(gen)*1e4:.1f}] bps")`,
      explanation: "This code trains β-VAE models with different β values (0.1, 1.0, 4.0) to demonstrate the reconstruction-regularization trade-off. With β=0.1, reconstruction is prioritized (low recon loss, high KL). With β=4.0, the latent space is heavily regularized (higher recon loss, lower KL, better disentanglement). The interpolation section encodes the calmest and most volatile training samples, then linearly interpolates between their latent codes at t=0, 0.25, 0.5, 0.75, 1.0. The decoded outputs show a smooth transition in volatility and mean return, demonstrating the VAE's structured latent space."
    },
    {
      type: "code",
      title: "Conditional VAE for Regime-Specific Generation",
      language: "python",
      code: `import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

np.random.seed(42)
torch.manual_seed(42)

# Three volatility regimes: low, medium, high
n_samples, seq_len, n_regimes = 900, 20, 3
labels = np.random.choice(n_regimes, size=n_samples, p=[0.5, 0.3, 0.2])
regime_params = {0: (0.0002, 0.003), 1: (0.0, 0.009), 2: (-0.0004, 0.022)}
returns = np.array([np.random.normal(regime_params[l][0], regime_params[l][1], seq_len)
                    for l in labels], dtype=np.float32)
data = torch.tensor(returns)
cond = F.one_hot(torch.tensor(labels), n_regimes).float()

class CVAE(nn.Module):
    def __init__(self, input_dim=20, cond_dim=3, latent_dim=6, hidden=48):
        super().__init__()
        # Encoder: input + condition -> latent
        self.enc = nn.Sequential(nn.Linear(input_dim + cond_dim, hidden), nn.ReLU(),
                                 nn.Linear(hidden, hidden), nn.ReLU())
        self.fc_mu = nn.Linear(hidden, latent_dim)
        self.fc_logvar = nn.Linear(hidden, latent_dim)
        # Decoder: latent + condition -> reconstruction
        self.dec = nn.Sequential(nn.Linear(latent_dim + cond_dim, hidden), nn.ReLU(),
                                 nn.Linear(hidden, hidden), nn.ReLU(),
                                 nn.Linear(hidden, input_dim))

    def encode(self, x, c):
        h = self.enc(torch.cat([x, c], dim=1))
        return self.fc_mu(h), self.fc_logvar(h)

    def decode(self, z, c):
        return self.dec(torch.cat([z, c], dim=1))

    def forward(self, x, c):
        mu, logvar = self.encode(x, c)
        z = mu + torch.exp(0.5 * logvar) * torch.randn_like(mu)
        return self.decode(z, c), mu, logvar

model = CVAE()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
print(f"CVAE parameters: {sum(p.numel() for p in model.parameters())}")

for epoch in range(1, 81):
    recon_x, mu, logvar = model(data, cond)
    recon_loss = F.mse_loss(recon_x, data, reduction="sum")
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    loss = recon_loss + kl_loss
    optimizer.zero_grad(); loss.backward(); optimizer.step()
    if epoch % 20 == 0:
        print(f"Epoch {epoch:3d} | Loss: {loss.item()/n_samples:.4f} | "
              f"Recon: {recon_loss.item()/n_samples:.4f} | KL: {kl_loss.item()/n_samples:.4f}")

# Generate regime-conditional scenarios
model.eval()
regime_names = ["Low Vol", "Medium Vol", "High Vol"]
print("\\n--- Conditional Generation ---")
with torch.no_grad():
    for r in range(n_regimes):
        c = F.one_hot(torch.tensor([r]), n_regimes).float().expand(10, -1)
        z = torch.randn(10, 6)
        gen = model.decode(z, c).numpy()
        vols = np.std(gen, axis=1) * 100
        means = np.mean(gen, axis=1) * 1e4
        print(f"\\n{regime_names[r]} (n=10 synthetic):")
        print(f"  Avg vol: {np.mean(vols):.4f}% | Avg mean: {np.mean(means):.2f} bps")
        print(f"  Vol range: [{np.min(vols):.4f}%, {np.max(vols):.4f}%]")

# Compare to training data statistics
print("\\n--- Training Data Reference ---")
for r in range(n_regimes):
    mask = labels == r
    true_vols = np.std(returns[mask], axis=1) * 100
    true_means = np.mean(returns[mask], axis=1) * 1e4
    print(f"{regime_names[r]}: vol={np.mean(true_vols):.4f}%, "
          f"mean={np.mean(true_means):.2f} bps (n={mask.sum()})")`,
      explanation: "This Conditional VAE conditions both the encoder and decoder on a one-hot volatility regime label (low/medium/high). The encoder concatenates the return window with the regime indicator before mapping to μ and log σ², while the decoder concatenates the latent sample z with the same indicator. This allows regime-specific generation: at inference time, we choose the desired regime, sample z ~ N(0,I), and decode conditioned on that regime. The output compares generated statistics (volatility, mean return) against training data for each regime, verifying the CVAE produces regime-appropriate synthetic scenarios for targeted stress testing."
    },
    {
      type: "quiz",
      questions: [
        {
          id: "vae-q1",
          question: "In the ELBO decomposition L = E_q[log p(x|z)] - KL(q(z|x) || p(z)), what happens if the KL term is driven to exactly zero during training?",
          options: [
            { id: "a", text: "The model achieves perfect reconstruction and generation" },
            { id: "b", text: "The encoder ignores the input x entirely, mapping all inputs to the prior N(0,I), causing posterior collapse" },
            { id: "c", text: "The decoder becomes deterministic and outputs the training set mean" },
            { id: "d", text: "The ELBO equals the exact log-likelihood log p(x)" }
          ],
          correctOptionId: "b",
          explanation: "When KL(q(z|x) || p(z)) = 0, the encoder output q(z|x) equals the prior p(z) = N(0,I) for all inputs x. This means the latent code z carries no information about x — the encoder has 'collapsed' to the prior. The decoder then receives uninformative z samples and can only output the marginal average of the training data. This is called posterior collapse and often occurs when the decoder is too powerful (e.g., autoregressive) or when KL annealing is not used."
        },
        {
          id: "vae-q2",
          question: "Given a VAE encoder that outputs μ = [0.8, -0.4] and log σ² = [-1.2, -0.6] for a 2D latent space, compute the KL divergence from the standard normal prior. Use KL = -0.5 × Σ(1 + log σ² - μ² - σ²).",
          options: [
            { id: "a", text: "0.362 nats" },
            { id: "b", text: "0.591 nats" },
            { id: "c", text: "0.724 nats" },
            { id: "d", text: "1.183 nats" }
          ],
          correctOptionId: "b",
          explanation: "For dimension 1: 1 + (-1.2) - 0.8² - exp(-1.2) = 1 - 1.2 - 0.64 - 0.3012 = -1.1412. For dimension 2: 1 + (-0.6) - (-0.4)² - exp(-0.6) = 1 - 0.6 - 0.16 - 0.5488 = -0.3088. Sum = -1.1412 + (-0.3088) = -1.450. KL = -0.5 × (-1.450) = 0.591 nats. The per-dimension contributions show dimension 1 (farther from prior with smaller variance and larger mean offset) contributes more to the KL penalty."
        },
        {
          id: "vae-q3",
          question: "Why does the reparameterization trick use z = μ + σ ⊙ ε instead of directly sampling z ~ N(μ, σ²)?",
          options: [
            { id: "a", text: "It produces lower-variance gradient estimates than any alternative" },
            { id: "b", text: "It reduces the computational cost of the forward pass by avoiding random number generation" },
            { id: "c", text: "It moves the stochasticity to an input variable ε independent of model parameters, making z a differentiable function of μ and σ that enables standard backpropagation" },
            { id: "d", text: "It ensures the latent distribution is always exactly Gaussian" }
          ],
          correctOptionId: "c",
          explanation: "Direct sampling z ~ N(μ, σ²) creates a stochastic node — the operation 'sample from this distribution' has no gradient with respect to the distribution's parameters. The reparameterization trick factors sampling into: (1) sample ε ~ N(0,I) which is parameter-free, and (2) compute z = μ + σ⊙ε which is a deterministic, differentiable function of μ and σ. Now ∂z/∂μ = I and ∂z/∂σ = diag(ε), so gradients flow through z to the encoder parameters via standard chain rule. It does also produce lower-variance gradients than REINFORCE, but the primary reason is enabling backpropagation at all."
        },
        {
          id: "vae-q4",
          question: "In a β-VAE with β = 5.0, what is the effect on the latent space compared to a standard VAE (β = 1.0)?",
          options: [
            { id: "a", text: "The latent space becomes 5× larger in volume" },
            { id: "b", text: "Each latent dimension is forced to encode 5 independent features" },
            { id: "c", text: "The stronger KL penalty pushes the encoder harder toward the prior, promoting disentanglement but potentially increasing reconstruction error" },
            { id: "d", text: "The model trains 5× faster due to stronger regularization gradients" }
          ],
          correctOptionId: "c",
          explanation: "With β = 5.0, the loss is L = Recon + 5 × KL. The 5× amplified KL penalty forces the encoder to keep q(z|x) very close to N(0,I). This pressure encourages disentanglement: the model learns to use each latent dimension for a single independent factor of variation, because 'wasting' capacity on redundant information is penalized more heavily. However, the stronger regularization means less information passes through the bottleneck, so reconstruction quality typically degrades. This is the fundamental β-VAE trade-off: disentanglement vs. reconstruction fidelity."
        },
        {
          id: "vae-q5",
          question: "A VAE trained on forex returns has reconstruction error (MSE) averaging 0.0001 on normal data. A new observation produces MSE = 0.0008. If you set an anomaly threshold at 3 standard deviations above the training mean (std = 0.00015), is this observation anomalous?",
          options: [
            { id: "a", text: "No, because 0.0008 < 0.001" },
            { id: "b", text: "Yes, because 0.0008 > threshold of 0.0001 + 3 × 0.00015 = 0.00055" },
            { id: "c", text: "Cannot determine without knowing the latent dimension" },
            { id: "d", text: "No, because the KL divergence must also exceed the threshold" }
          ],
          correctOptionId: "b",
          explanation: "The anomaly threshold is mean + 3 × std = 0.0001 + 3 × 0.00015 = 0.0001 + 0.00045 = 0.00055. The observation's reconstruction error of 0.0008 exceeds this threshold (0.0008 > 0.00055), so it is flagged as anomalous. The intuition: the VAE learned to compress and reconstruct normal market patterns well, so high reconstruction error indicates the observation comes from a pattern the model hasn't seen — a potential regime change, flash crash, or data error. In practice, you might also incorporate the KL term into the anomaly score for a more comprehensive measure."
        },
        {
          id: "vae-q6",
          question: "What happens to a standard VAE (β = 1) as β → 0 in the limit?",
          options: [
            { id: "a", text: "It becomes a perfect generative model with zero reconstruction error and zero KL divergence" },
            { id: "b", text: "It converges to the true posterior p(z|x) because the ELBO gap vanishes" },
            { id: "c", text: "It degenerates into a deterministic autoencoder: perfect reconstruction but no meaningful latent structure for generation, since the encoder can map to arbitrary regions without penalty" },
            { id: "d", text: "The gradients vanish and training stops" }
          ],
          correctOptionId: "c",
          explanation: "As β → 0, the loss becomes L ≈ Recon + 0 × KL = Recon only. Without any KL penalty, the encoder is free to map each input to a unique, arbitrary point in latent space (or collapse variance to zero, making it deterministic). Reconstruction becomes near-perfect, but the latent space has no structure: points are scattered without regard to the prior N(0,I), gaps exist between encoded points, and sampling z ~ N(0,I) for generation will land in 'dead zones' that decode to meaningless outputs. This is exactly a standard autoencoder — great for compression, useless for generation."
        },
        {
          id: "vae-q7",
          question: "In a Conditional VAE for forex, you condition on regime label y = 'high_volatility'. At generation time, you sample z ~ N(0,I) and decode with y = 'low_volatility' instead. What output do you expect?",
          options: [
            { id: "a", text: "An exact copy of the high-volatility training data" },
            { id: "b", text: "A sample consistent with the low-volatility regime, because the decoder uses y to determine output characteristics regardless of z" },
            { id: "c", text: "A corrupted hybrid that is neither high-vol nor low-vol" },
            { id: "d", text: "An error, because z was sampled without conditioning on y" }
          ],
          correctOptionId: "b",
          explanation: "In a well-trained CVAE, the decoder p_θ(x|z, y) uses the condition y to set the overall output characteristics (mean return, volatility level) while z provides the specific variation within that regime. Since z ~ N(0,I) is regime-agnostic (the prior doesn't depend on y), the condition y = 'low_volatility' will steer the decoder to generate low-volatility outputs. This is the power of conditional generation: you explicitly control regime characteristics while z provides diverse realizations within that regime."
        }
      ]
    },
    {
      type: "practice",
      title: "Anomaly Detection with VAE Reconstruction Error",
      description: "Train a VAE on historical forex return windows from a stable period. Compute the reconstruction error distribution (mean and standard deviation) on the training set. Then feed recent or held-out data through the trained VAE and flag any windows whose reconstruction error exceeds the mean + 3σ threshold as anomalous. Experiment with different latent dimensions (4, 8, 16) and observe how anomaly detection sensitivity changes. Visualize the reconstruction error time series and overlay detected anomalies. Consider: does higher latent dimension improve detection, or does it cause the VAE to overfit and miss anomalies?",
      catalogModelId: "vae"
    },
    {
      type: "practice",
      title: "Stress Testing with Conditional Scenario Generation",
      description: "Build a Conditional VAE conditioned on three volatility regimes (low, medium, high) using historical forex data. After training, generate 1000 synthetic return sequences for each regime by sampling z ~ N(0,I) and decoding with each regime label. Validate the generated scenarios by comparing their statistical properties (mean, standard deviation, skewness, kurtosis, autocorrelation) against real data from each regime. Then use latent space interpolation between the 'low' and 'high' regime centroids to generate a continuum of stress scenarios at t = 0.0, 0.1, ..., 1.0. Plot how portfolio VaR (Value at Risk) at the 99th percentile changes across the interpolation path. This gives risk managers a parametric stress-testing lever.",
      catalogModelId: "vae"
    }
  ]
}
