// Generated by scripts/build_study_index.mjs: one import per handler file. Do not edit by hand.
import type { StudyHandler } from "../types";
import candlePatternGallery from "./candle-pattern-gallery";
import candlePatternScorecard from "./candle-pattern-scorecard";
import candlePatternVision from "./candle-pattern-vision";
import candleShapeStandouts from "./candle-shape-standouts";
import candleVectors from "./candle-vectors";
import candleVocabulary from "./candle-vocabulary";
import candlestickPatternCensus from "./candlestick-pattern-census";
import candlestickPatternExemplars from "./candlestick-pattern-exemplars";
import candlestickPatternImages from "./candlestick-pattern-images";
import chartCnnArithmeticPatterns from "./chart-cnn-arithmetic-patterns";
import chartCnnDirectionNullResult from "./chart-cnn-direction-null-result";
import chartCnnPatternRecognition from "./chart-cnn-pattern-recognition";
import chartCompanion from "./chart-companion";
import contractSpecifications from "./contract-specifications";
import crossoverStrategy from "./crossover-strategy";
import dataLifecycleAudit from "./data-lifecycle-audit";
import directionLabelsOnCandles from "./direction-labels-on-candles";
import empiricalSourceOfTruth from "./empirical-source-of-truth";
import eurusdBarsAndLabels from "./eurusd-bars-and-labels";
import eurusdReactivity from "./eurusd-reactivity";
import featureLadderWhatToEncode from "./feature-ladder-what-to-encode";
import finbertSentiment from "./finbert-sentiment";
import frozenCandleEncoder from "./frozen-candle-encoder";
import fxPairSignals from "./fx-pair-signals";
import hwmaStability from "./hwma-stability";
import indicatorStudy from "./indicator-study";
import labelAudit1m from "./label-audit-1m";
import labelCatalog from "./label-catalog";
import labelOverlay from "./label-overlay";
import lakeAudit from "./lake-audit";
import machineHealth from "./machine-health";
import marketBarsValidation from "./market-bars-validation";
import marketSeriesExplorer from "./market-series-explorer";
import mnqEda30m from "./mnq-eda-30m";
import modelCycleRuns from "./model-cycle-runs";
import multimodalModel from "./multimodal-model";
import pathGeometryStudy from "./path-geometry-study";
import patternCasebook from "./pattern-casebook";
import processCensus from "./process-census";
import quantBarsToTensor from "./quant-bars-to-tensor";
import quantOosResults from "./quant-oos-results";
import regimeGatedCrossover from "./regime-gated-crossover";
import regressionTabPerformance from "./regression-tab-performance";
import singleCandleRecognizer from "./single-candle-recognizer";
import slopeSignalBacktest from "./slope-signal-backtest";
import storageFormatInventory from "./storage-format-inventory";
import taStrategy600Ticks from "./ta-strategy-600-ticks";
import tailClocks from "./tail-clocks";
import talibIndicatorCatalogue from "./talib-indicator-catalogue";
import timescaledbLoadMonitor from "./timescaledb-load-monitor";
import trainingEnvironment from "./training-environment";
import trendStateCalibration from "./trend-state-calibration";
import vectorSpaceExplained from "./vector-space-explained";
import volatilityToPriceRange from "./volatility-to-price-range";
import volumeCandleAnatomy from "./volume-candle-anatomy";

export const STUDY_HANDLERS: StudyHandler[] = [
  candlePatternGallery as StudyHandler,
  candlePatternScorecard as StudyHandler,
  candlePatternVision as StudyHandler,
  candleShapeStandouts as StudyHandler,
  candleVectors as StudyHandler,
  candleVocabulary as StudyHandler,
  candlestickPatternCensus as StudyHandler,
  candlestickPatternExemplars as StudyHandler,
  candlestickPatternImages as StudyHandler,
  chartCnnArithmeticPatterns as StudyHandler,
  chartCnnDirectionNullResult as StudyHandler,
  chartCnnPatternRecognition as StudyHandler,
  chartCompanion as StudyHandler,
  contractSpecifications as StudyHandler,
  crossoverStrategy as StudyHandler,
  dataLifecycleAudit as StudyHandler,
  directionLabelsOnCandles as StudyHandler,
  empiricalSourceOfTruth as StudyHandler,
  eurusdBarsAndLabels as StudyHandler,
  eurusdReactivity as StudyHandler,
  featureLadderWhatToEncode as StudyHandler,
  finbertSentiment as StudyHandler,
  frozenCandleEncoder as StudyHandler,
  fxPairSignals as StudyHandler,
  hwmaStability as StudyHandler,
  indicatorStudy as StudyHandler,
  labelAudit1m as StudyHandler,
  labelCatalog as StudyHandler,
  labelOverlay as StudyHandler,
  lakeAudit as StudyHandler,
  machineHealth as StudyHandler,
  marketBarsValidation as StudyHandler,
  marketSeriesExplorer as StudyHandler,
  mnqEda30m as StudyHandler,
  modelCycleRuns as StudyHandler,
  multimodalModel as StudyHandler,
  pathGeometryStudy as StudyHandler,
  patternCasebook as StudyHandler,
  processCensus as StudyHandler,
  quantBarsToTensor as StudyHandler,
  quantOosResults as StudyHandler,
  regimeGatedCrossover as StudyHandler,
  regressionTabPerformance as StudyHandler,
  singleCandleRecognizer as StudyHandler,
  slopeSignalBacktest as StudyHandler,
  storageFormatInventory as StudyHandler,
  taStrategy600Ticks as StudyHandler,
  tailClocks as StudyHandler,
  talibIndicatorCatalogue as StudyHandler,
  timescaledbLoadMonitor as StudyHandler,
  trainingEnvironment as StudyHandler,
  trendStateCalibration as StudyHandler,
  vectorSpaceExplained as StudyHandler,
  volatilityToPriceRange as StudyHandler,
  volumeCandleAnatomy as StudyHandler,
];
