/**
 * Snapshot of GET /api/model-catalog/trainable, taken 2026-08-05.
 *
 * Checked in so the coverage guarantee is testable without a running
 * server. Regenerate via the command in the Wave 1 plan (Task 1) when the
 * catalog changes; coverage.test.ts then fails for any new key until it
 * is researched.
 */

export interface CatalogKeyRow {
  key: string;
  name: string;
  templateId: string | null;
  category: string | null;
}

export const CATALOG_KEYS: readonly CatalogKeyRow[] = [
  { key: "xgboost+direction_classifier", name: "XGBoost Direction Classifier", templateId: null, category: "Supervised" },
  { key: "transformer_2s+range_classifier", name: "Two-Stream Transformer + Range-Bucket (HPO)", templateId: null, category: "neural-network" },
  { key: "transformer_tiny+direction_classifier", name: "Tiny Transformer + Daily Direction (HPO)", templateId: null, category: "neural-network" },
  { key: "primitives_cnn+multi_head", name: "CNN+Transformer Primitives (Multi-Head)", templateId: null, category: "neural-network" },
  { key: "temporal_fusion_transformer+direction_classifier", name: "Temporal Fusion Transformer (temporal_fusion_transformer)", templateId: null, category: "neural-network" },
  { key: "adversarial-autoencoder", name: "Adversarial Autoencoder (AAE)", templateId: "pytorch_autoencoder", category: "generative" },
  { key: "biggan", name: "BigGAN", templateId: "pytorch_mlp", category: "generative" },
  { key: "conditional-gan-cgan", name: "Conditional Generative Adversarial Network (cGAN)", templateId: "pytorch_mlp", category: "generative" },
  { key: "cyclegan", name: "CycleGAN", templateId: "pytorch_mlp", category: "generative" },
  { key: "generative-adversarial-network-gan", name: "Generative Adversarial Network (GAN)", templateId: "pytorch_mlp", category: "generative" },
  { key: "stylegan", name: "StyleGAN", templateId: "pytorch_mlp", category: "generative" },
  { key: "wasserstein-gan-wgan", name: "Wasserstein Generative Adversarial Network (WGAN)", templateId: "pytorch_mlp", category: "generative" },
  { key: "autoregressive-model-pixelrnn-pixelcnn", name: "Autoregressive Models (PixelRNN and PixelCNN)", templateId: "pytorch_mlp", category: "generative" },
  { key: "transformer-based-generator-e-g-gpt", name: "Transformer-Based Generator (e.g., GPT)", templateId: "transformer_seq", category: "generative" },
  { key: "diffusion-model", name: "Diffusion Models", templateId: "pytorch_mlp", category: "generative" },
  { key: "perceptual-loss-generator", name: "Perceptual Loss Generator", templateId: "pytorch_mlp", category: "generative" },
  { key: "score-based-generative-model", name: "Score-Based Generative Model", templateId: "pytorch_mlp", category: "generative" },
  { key: "unet-generator-used-in-diffusion", name: "U-Net Generator (Used in Diffusion)", templateId: "pytorch_mlp", category: "generative" },
  { key: "energy-based-model", name: "Energy-Based Model", templateId: null, category: "generative" },
  { key: "bayesian-generator", name: "Bayesian Generator", templateId: "pytorch_mlp", category: "generative" },
  { key: "deep-boltzmann-machine-generator", name: "Deep Boltzmann Machine Generator", templateId: "pytorch_mlp", category: "generative" },
  { key: "masked-autoencoder-for-distribution-learning", name: "Masked Autoencoder for Distribution Learning", templateId: "pytorch_autoencoder", category: "generative" },
  { key: "neural-ode-generator", name: "Neural ODE Generator", templateId: "pytorch_mlp", category: "generative" },
  { key: "normalizing-flow", name: "Normalizing Flow", templateId: "pytorch_mlp", category: "generative" },
  { key: "variational-autoencoder-vae", name: "Variational Autoencoder (VAE)", templateId: "pytorch_vae", category: "generative" },
  { key: "rnn-cnn-hybrid", name: "RNN-CNN Hybrid", templateId: "pytorch_cnn", category: "hybrid-composite" },
  { key: "stacked-ensemble-model", name: "Stacked Ensemble Model", templateId: "sklearn", category: "hybrid-composite" },
  { key: "autoencoder-gan-fusion", name: "Autoencoder-GAN Fusion", templateId: "pytorch_autoencoder", category: "hybrid-composite" },
  { key: "bayesian-neural-hybrid-model", name: "Bayesian-Neural Hybrid Model", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "gnn-reinforcement-learner", name: "GNN + Reinforcement Learner Hybrid", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "attention-weighted-forecast-stack", name: "Attention-Weighted Forecast Stack", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "hierarchical-task-oriented-agent", name: "Hierarchical Task-Oriented Agent", templateId: null, category: "hybrid-composite" },
  { key: "multi-modal-reasoning-agent", name: "Multi-Modal Reasoning Agent", templateId: null, category: "hybrid-composite" },
  { key: "spatiotemporal-fusion-network", name: "Spatiotemporal Fusion Network", templateId: "temporal_fusion_transformer", category: "hybrid-composite" },
  { key: "differentiable-logic-layer", name: "Differentiable Logic Layer", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "meta-learned-symbolic-router", name: "Meta-Learned Symbolic Router", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "neuro-symbolic-model", name: "Neuro-Symbolic Model", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "probabilistic-program-deepnet", name: "Probabilistic Program + DeepNet", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "residual-learning-over-rules", name: "Residual Learning over Rules", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "rule-augmented-neural-net", name: "Rule-Augmented Neural Net", templateId: "pytorch_mlp", category: "hybrid-composite" },
  { key: "denoising-autoencoder", name: "Denoising Autoencoder", templateId: "pytorch_autoencoder", category: "self-supervised" },
  { key: "self-distillation-without-labels", name: "Self-Distillation Without Labels", templateId: "pytorch_mlp", category: "self-supervised" },
  { key: "barlow-twins", name: "Barlow Twins", templateId: null, category: "self-supervised" },
  { key: "byol-bootstrap-your-own-latent", name: "BYOL (Bootstrap Your Own Latent)", templateId: null, category: "self-supervised" },
  { key: "contrastive-learning-simclr-moco", name: "Contrastive Learning (SimCLR, MoCo)", templateId: null, category: "self-supervised" },
  { key: "cross-view-prediction", name: "Cross-View Prediction", templateId: null, category: "self-supervised" },
  { key: "momentum-contrast-moco-v3", name: "Momentum Contrast (MoCo v3)", templateId: "transformer_seq", category: "self-supervised" },
  { key: "patch-level-contrastive-learning-e-g-dino", name: "Patch-level Contrastive Learning (e.g., DINO)", templateId: "transformer_seq", category: "self-supervised" },
  { key: "self-augmented-contrastive-encoder", name: "Self-Augmented Contrastive Encoder", templateId: null, category: "self-supervised" },
  { key: "simsiam", name: "SimSiam (Simple Siamese Representation Learning)", templateId: null, category: "self-supervised" },
  { key: "swav-swapped-assignments", name: "SwAV (Swapped Assignments)", templateId: null, category: "self-supervised" },
  { key: "self-supervised-gans", name: "Self-Supervised GANs", templateId: "pytorch_mlp", category: "self-supervised" },
  { key: "masked-autoencoder-mae", name: "Masked Autoencoder (MAE)", templateId: "pytorch_autoencoder", category: "self-supervised" },
  { key: "masked-graph-modeling", name: "Masked Graph Modeling", templateId: "pytorch_mlp", category: "self-supervised" },
  { key: "masked-language-modeling-bert-style", name: "Masked Language Modeling (BERT-style)", templateId: "transformer_seq", category: "self-supervised" },
  { key: "context-prediction-cpc", name: "Contrastive Predictive Coding (CPC)", templateId: null, category: "self-supervised" },
  { key: "predictive-coding-models", name: "Predictive Coding Models", templateId: null, category: "self-supervised" },
  { key: "rotation-prediction-rotnet", name: "Rotation Prediction (RotNet)", templateId: "pytorch_mlp", category: "self-supervised" },
  { key: "self-predictive-representations-spr", name: "Self-Predictive Representations (SPR)", templateId: null, category: "self-supervised" },
  { key: "transformer-based-self-supervision", name: "Transformer-based Self-Supervision", templateId: "transformer_seq", category: "self-supervised" },
  { key: "semi-supervised-clustering", name: "Semi-Supervised Clustering", templateId: null, category: "semi-supervised" },
  { key: "consistency-regularization-e-g-model-mean-teacher", name: "Consistency Regularization (Π-model, Mean Teacher)", templateId: null, category: "semi-supervised" },
  { key: "fixmatch", name: "FixMatch", templateId: null, category: "semi-supervised" },
  { key: "mixmatch", name: "MixMatch", templateId: "transformer_seq", category: "semi-supervised" },
  { key: "virtual-adversarial-training-vat", name: "Virtual Adversarial Training (VAT)", templateId: null, category: "semi-supervised" },
  { key: "hybrid-generative-discriminative-ssl", name: "Hybrid Generative-Discriminative Semi-Supervised Learning", templateId: null, category: "semi-supervised" },
  { key: "ladder-network", name: "Ladder Network", templateId: "pytorch_mlp", category: "semi-supervised" },
  { key: "semi-supervised-gan-sgan", name: "Semi-Supervised Generative Adversarial Network (SGAN)", templateId: "pytorch_mlp", category: "semi-supervised" },
  { key: "graph-based-semi-supervised-learning", name: "Graph-Based Semi-Supervised Learning", templateId: null, category: "semi-supervised" },
  { key: "label-propagation", name: "Label Propagation", templateId: null, category: "semi-supervised" },
  { key: "label-spreading", name: "Label Spreading", templateId: null, category: "semi-supervised" },
  { key: "manifold-regularization", name: "Manifold Regularization", templateId: "pytorch_mlp", category: "semi-supervised" },
  { key: "co-training-dual-view", name: "Co-Training (Dual View)", templateId: null, category: "semi-supervised" },
  { key: "multi-view-learning", name: "Multi-View Learning", templateId: null, category: "semi-supervised" },
  { key: "entropy-minimization", name: "Entropy Minimization", templateId: null, category: "semi-supervised" },
  { key: "semi-supervised-svm-s3vm", name: "Semi-Supervised Support Vector Machine (S3VM)", templateId: "sklearn", category: "semi-supervised" },
  { key: "pseudo-labeling", name: "Pseudo-Labeling", templateId: "pytorch_mlp", category: "semi-supervised" },
  { key: "self-training-classifier", name: "Self-Training Classifier", templateId: "pytorch_mlp", category: "semi-supervised" },
  { key: "tri-training", name: "Tri-Training", templateId: null, category: "semi-supervised" },
  { key: "catboost", name: "CatBoost", templateId: "sklearn", category: "supervised" },
  { key: "gradient-boosting-machine-gbm", name: "Gradient Boosting Machine (GBM)", templateId: "sklearn", category: "supervised" },
  { key: "lightgbm", name: "LightGBM", templateId: "sklearn", category: "supervised" },
  { key: "xgboost", name: "XGBoost", templateId: "sklearn", category: "supervised" },
  { key: "calibrated-classifier", name: "Calibrated Classifier", templateId: "sklearn", category: "supervised" },
  { key: "random-forest", name: "Random Forest", templateId: "sklearn", category: "supervised" },
  { key: "stacked-generalization-model", name: "Stacked Generalization Model", templateId: null, category: "supervised" },
  { key: "bayesian-ridge-regression", name: "Bayesian Ridge Regression", templateId: "sklearn", category: "supervised" },
  { key: "elasticnet-regression", name: "ElasticNet Regression", templateId: "sklearn", category: "supervised" },
  { key: "lars-least-angle-regression", name: "Least Angle Regression (LARS)", templateId: "sklearn", category: "supervised" },
  { key: "lasso-regression", name: "Lasso Regression", templateId: "sklearn", category: "supervised" },
  { key: "linear-regression", name: "Linear Regression", templateId: null, category: "supervised" },
  { key: "logistic-regression", name: "Logistic Regression", templateId: "sklearn", category: "supervised" },
  { key: "ordinal-regression", name: "Ordinal Regression", templateId: "sklearn", category: "supervised" },
  { key: "probit-regression", name: "Probit Regression", templateId: "sklearn", category: "supervised" },
  { key: "quantile-regression", name: "Quantile Regression", templateId: null, category: "supervised" },
  { key: "ridge-regression", name: "Ridge Regression", templateId: "sklearn", category: "supervised" },
  { key: "stochastic-gradient-descent-sgd", name: "Stochastic Gradient Descent (SGD)", templateId: "sklearn", category: "supervised" },
  { key: "support-vector-machine-svm", name: "Support Vector Machine (SVM)", templateId: "sklearn", category: "supervised" },
  { key: "isolation-forest-anomaly-detection", name: "Isolation Forest (Anomaly Detection)", templateId: "sklearn", category: "unsupervised" },
  { key: "lof-local-outlier-factor", name: "Local Outlier Factor (LOF)", templateId: null, category: "unsupervised" },
  { key: "one-class-svm", name: "One-Class SVM", templateId: "sklearn", category: "unsupervised" },
  { key: "robust-covariance-estimation", name: "Robust Covariance Estimation", templateId: null, category: "unsupervised" },
  { key: "affinity-propagation", name: "Affinity Propagation", templateId: null, category: "unsupervised" },
  { key: "dbscan-density-based-spatial-clustering", name: "DBSCAN (Density-Based Spatial Clustering of Applications with Noise)", templateId: null, category: "unsupervised" },
  { key: "gaussian-mixture-model-gmm", name: "Gaussian Mixture Model (GMM)", templateId: null, category: "unsupervised" },
  { key: "hierarchical-clustering-agglomerative-divisive", name: "Hierarchical Clustering (Agglomerative, Divisive)", templateId: null, category: "unsupervised" },
  { key: "k-means-clustering", name: "K-Means Clustering", templateId: null, category: "unsupervised" },
  { key: "mean-shift-clustering", name: "Mean Shift Clustering", templateId: null, category: "unsupervised" },
  { key: "spectral-clustering", name: "Spectral Clustering", templateId: null, category: "unsupervised" },
  { key: "independent-component-analysis-ica", name: "Independent Component Analysis (ICA)", templateId: null, category: "unsupervised" },
  { key: "non-negative-matrix-factorization-nmf", name: "Non-Negative Matrix Factorization (NMF)", templateId: null, category: "unsupervised" },
  { key: "principal-component-analysis-pca", name: "Principal Component Analysis (PCA)", templateId: null, category: "unsupervised" },
  { key: "manifold-learning-isomap-lle", name: "Manifold Learning (Isomap, LLE)", templateId: null, category: "unsupervised" },
  { key: "t-sne-t-distributed-stochastic-neighbor-embedding", name: "t-Distributed Stochastic Neighbor Embedding (t-SNE)", templateId: null, category: "unsupervised" },
  { key: "umap-uniform-manifold-approximation-and-projection", name: "Uniform Manifold Approximation and Projection (UMAP)", templateId: null, category: "unsupervised" },
  { key: "autoencoder-unsupervised", name: "Autoencoder (Unsupervised)", templateId: "pytorch_autoencoder", category: "unsupervised" },
  { key: "deep-clustering-network", name: "Deep Clustering Network (DCN)", templateId: "pytorch_mlp", category: "unsupervised" },
  { key: "self-organizing-maps-som", name: "Self-Organizing Maps (SOM)", templateId: "pytorch_mlp", category: "unsupervised" },
  { key: "self-attention-mechanism", name: "Self-Attention Mechanism", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "slot-attention-network", name: "Slot Attention Network", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "transformer-encoder-decoder", name: "Transformer (Encoder-Decoder)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "vision-transformer-vit", name: "Vision Transformer (ViT)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "convolutional-neural-network-cnn", name: "Convolutional Neural Network (CNN)", templateId: "pytorch_cnn", category: "neural-network" },
  { key: "densenet-densely-connected-cnn", name: "DenseNet (Densely Connected CNN)", templateId: "pytorch_cnn", category: "neural-network" },
  { key: "residual-neural-network-resnet", name: "Residual Neural Network (ResNet)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "u-net", name: "U-Net", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "feedforward-neural-network-fnn", name: "Feedforward Neural Network (FNN)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "multilayer-perceptron-mlp", name: "Multilayer Perceptron (MLP)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "autoencoder-ae", name: "Autoencoder (AE)", templateId: "pytorch_autoencoder", category: "neural-network" },
  { key: "neural-ordinary-differential-equation-neural-ode", name: "Neural Ordinary Differential Equation (Neural ODE)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "graph-attention-network-gat", name: "Graph Attention Network (GAT)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "graph-convolutional-network-gcn", name: "Graph Convolutional Network (GCN)", templateId: "pytorch_cnn", category: "neural-network" },
  { key: "graph-neural-network-gnn", name: "Graph Neural Network (GNN)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "hypernetwork", name: "Hypernetwork", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "mixture-of-experts", name: "Mixture of Experts (MoE)", templateId: "pytorch_mlp", category: "neural-network" },
  { key: "moe-composite", name: "Mixture of Experts (Composite)", templateId: "composite_moe", category: "hybrid-composite" },
  { key: "stacking-composite", name: "Stacking Ensemble (Composite)", templateId: "composite_stacking", category: "hybrid-composite" },
  { key: "voting-composite", name: "Voting Ensemble (Composite)", templateId: "composite_voting", category: "hybrid-composite" },
  { key: "multimodal-composite", name: "Multimodal Encoder Fusion (Composite)", templateId: "composite_multimodal", category: "hybrid-composite" },
  { key: "temporal-fusion-transformer", name: "Temporal Fusion Transformer", templateId: "temporal_fusion_transformer", category: "neural-network" },
];
