// Generated by scripts/build_study_index.mjs: one import per handler file. Do not edit by hand.
import type { StudyHandler } from "../types";
import candlePatternScorecard from "./candle-pattern-scorecard";

export const STUDY_HANDLERS: StudyHandler[] = [
  candlePatternScorecard as StudyHandler,
];
